#ifndef __PY_MB_h__
#define __PY_MB_h__
#include "pyinput.h"


/* ºº×ÖÅÅÁĞ±í */
const char PY_mb_space []={""};
const char PY_mb_a     []={"°¡°¢ëçß¹ï¹…àÄåHºÇëç"};
const char PY_mb_ai    []={"°®°£°¤°¥°¦°§°¨°©°ª°«°¬°­°¯ŞßàÈàÉæÈè¨êÓíÁïÍö°"};
const char PY_mb_an    []={"°²°³°´°µ°¶°¸°°°±ÚÏ°·ÛûŞîáíâÖèñï§ğÆ÷ö"};
const char PY_mb_ang   []={"°º°»°¹óa"};
const char PY_mb_ao    []={"°¼°½°¾°¿°À°Á°Â°Ã°ÄÛêŞÖà»òüöË÷¡÷éá®âÚåÛæÁæñéáñú"};
const char PY_mb_ba    []={"°Ë°Í°Ö°Î°Å°Æ°Ç°È°É°Ê°Ì°Ï°Ğ°Ñ°Ò°Ó°Ô°ÕÜØİÃá±å±îÙôÎöÑ÷É"};
const char PY_mb_bai   []={"°×°Ø°Ù°Ú°Û°Ü°İ°Ş²®Şãêş"};
const char PY_mb_ban   []={"°ë°ì°ß°à°á°â°ã°ä°å°æ°ç°è°é°ê°íÚæÛàêÚîÓñ£ñ­ô²"};
const char PY_mb_bang  []={"°î°ï°ğ°ñ°ò°ó°ô°õ°ö°÷°ø°ùİòäº"};
const char PY_mb_bao   []={"°ü±¦±£±§±¨±©°ú°û°ı°ş±¡±¢±¤±¥±ª±«±¬ÅÙÅÚÙèİáæßìÒğ±ñÙõÀöµ"};
const char PY_mb_bei   []={"±³±´±±±¶±­±®±¯±°±²±µ±·±¸±¹±º±»±ÛØÃÚéÚıÛıİÉİíßÂã£íÕğÇñØöÍ÷¹"};;
const char PY_mb_ben   []={"±¾±¿±¼±½ÛÎÛĞêÚï¼"};
const char PY_mb_beng  []={"°ö±À±Á±Â±Ã±Ä±ÅÜ¡àÔê´"};
const char PY_mb_bi    []={"±Æ±Ç±È±É±Ê±Ë±Ì±Í±Î±Ï±Ğ±Ñ±Ò±Ó±Ô±ÕØ°±Ö±×±Ø±Ù±Ú±Û±Ü±İÃØÃÚÙÂÛıÜÅÜêİ©İÉŞµßÁßÙáùâØã¹ääå¨åöåşæ¾æÔèµêÚî¯îéïõñÔóÙóëó÷ô°ôÅõÏ÷Â"};
const char PY_mb_bian  []={"±ß±à±á±ã±ä±å±Ş±â±æ±ç±è±éØÒÛÍÜĞâíãêçÂìÔí¾íÜñ¹ñÛòùóÖöı"};
const char PY_mb_biao  []={"±í±ê±ë±ìæ»æôè¼ì©ì­ì®ïÚïğñ¦ñÑ÷§÷Ô"};
const char PY_mb_bie   []={"±ğ±î±ï±ñõ¿"};
const char PY_mb_bin   []={"±ò±ó±ô±õ±ö±÷ÙÏáÙçÍçãéÄéëë÷ïÙ÷Æ÷Ş"};
const char PY_mb_bing  []={"±ø±ù±ú±û±ü±ı±ş²¡²¢ÆÁÙ÷ÙûÚûŞğéÄ"};
const char PY_mb_bo    []={"°Ø°Ù°ş±¡²©²£²¤²·²¥²¦²§²¨²ª²«²¬²­²®²¯²°²±²²²³²´²µØÃÙñŞ¬à£âÄéŞë¢íçîàğ¾ô¤õÀõËõÛ"};
const char PY_mb_bu    []={"²»²¼²½±¤²¶²·²¸²¹²º²¾²¿²ÀÆÒß²åÍê³êÎîĞîßõ³"};
const char PY_mb_ca    []={"²Áàêíå"};
const char PY_mb_cai   []={"²Å²Æ²Ç²Â²Ã²Ä²È²É²Ê²Ë²Ì"};
const char PY_mb_can   []={"²Í²Î²Ï²Ğ²Ñ²Ò²Óåîæîè²ôÓ÷õ"};
const char PY_mb_cang  []={"²Ô²Õ²Ö²×²ØØ÷"};
const char PY_mb_cao   []={"²İ²Ù²Ú²Û²ÜÜ³àĞäîó©ô½"};
const char PY_mb_ce    []={"²à²á²â²Ş²ßâü"};
const char PY_mb_cen   []={"²Îá¯ä¹"};
const char PY_mb_ceng  []={"²ã²äÔøàá"};
const char PY_mb_cha   []={"²å²æ²ç²è²é²ê²ë²ì²í²î²ïÉ²ÔûñÃàêâªâÇãâæ±è¾é«é¶éßïÊïï"};
const char PY_mb_chai  []={"²î²ğ²ñ²òÙ­îÎğûò²ö·"};
const char PY_mb_chan  []={"²ú²û²ü²ó²ô²õ²ö²÷²ø²ùåîµ¥ÙæÚÆİÛâÜâãäıå¤åñæ¿êèìøïâó¸õğ"};
const char PY_mb_chang []={"³¤³§²ı²ş³¡³¢³£³¥³¦³¨³©³ª³«ØöÛËÜÉİÅáäâêã®ãÑæ½æÏêÆë©öğ"};
const char PY_mb_chao  []={"³¬³­³®³¯³°³±³²³³³´´Â½Ëâ÷êËñé"};
const char PY_mb_che   []={"³µ³¶³·³¸³¹³ºÛååøíº"};
const char PY_mb_chen  []={"³»³¼³½³¾³¿³À³Á³Â³Ã³Ä³ÆÚÈÚßŞÓàÁå·è¡é´í×ö³"};
const char PY_mb_cheng []={"³Å³Æ³Ç³È³É³Ê³Ë³Ì³Í³Î³Ï³Ğ³Ñ³Ò³ÓÊ¢Ø©ÛôàááçèÇèßëóîªîñîõñÎòÉõ¨"};
const char PY_mb_chi   []={"³Ô³Õ³Ö³×³Ø³Ù³Ú³Û³Ü³İ³Ş³ß³à³á³â³ãó×ß³ßêÙÑÛæÜ¯Üİà´àÍáÜâÁæÊë·í÷ğ·ñ¡ñİò¿ó¤óøôùõØ÷Î"};
const char PY_mb_chong []={"³ä³å³æ³ç³èÖÖÖØÜûâçã¿ï¥ô©ô¾öÅ"};
const char PY_mb_chou  []={"³é³ê³ó³ë³ì³í³î³ï³ğ³ñ³ò³ôÙ±àüã°ñ¬öÅ"};
const char PY_mb_chu   []={"³ö³õ³÷³ø³ù³ú³û³ü³ı³ş´¡´¢´£´¤´¥´¦ĞóØ¡Û»âğãÀç©èÆèúéËñÒòÜõé÷í"};
const char PY_mb_chuai []={"´§ŞõàÜëúõß"};
const char PY_mb_chuan []={"´¨´©´ª´«´¬´­´®â¶å×çİë°îËô­"};
const char PY_mb_chuang[]={"´¯´°´±´²´³´´âëğÚ"};
const char PY_mb_chui  []={"´µ´¶´·´¸´¹Úïé¢é³"};
const char PY_mb_chun  []={"´º´»´¼´½´¾´¿´Àİ»ğÈòí"};
const char PY_mb_chuo  []={"´Á´Âà¨åÁê¡õÖöº"};
const char PY_mb_ci    []={"´Ë´Ì´Í´ÎËÅ²î´Ã´Ä´Å´Æ´Ç´È´É´Ê×ÈÜëßÚìôğËôÒôÙ"};
const char PY_mb_cong  []={"´Ó´Ô´Ï´Ğ´Ñ´ÒÜÊäÈæõçıè®èÈ"};
const char PY_mb_cou   []={"´Õé¨ê£ëí"};
const char PY_mb_cu    []={"´Ö´×´Ø´ÙİıáŞâ§éãõ¡õ¾õí"};
const char PY_mb_cuan  []={"´Ú´Û´ÜÔÜÙàß¥ìàïé"};
const char PY_mb_cui   []={"´İ´Ş´ß´à´á´â´ã´äİÍßıã²è­éÁë¥ö¿"};
const char PY_mb_cun   []={"´å´æ´çââñå"};
const char PY_mb_cuo   []={"´è´é´ê´ë´ì´íØÈáÏëâï±ïóğîğûõºõãõò"};
const char PY_mb_da    []={"´ó´î´ï´ğ´ñ´òŞÇßÕàªâòæ§í³ğãñ×óÎ÷°÷²"};
const char PY_mb_dai   []={"´ó´ô´õ´ö´÷´ø´ù´ú´û´ü´ı´şµ¡÷ìÜ¤ß°ß¾á·åÊææçªçé"};
const char PY_mb_dan   []={"µ¢µ£µ¤µ¥µ¦µ§µ¨µ©µªµ«µ¬µ­µ®µ¯µ°ÉÄÊ¯ÙÙİÌà¢å£ééêæíñğãğ÷ñõóì"};
const char PY_mb_dang  []={"µ±µ²µ³µ´µµÚÔÛÊİĞå´í¸îõñÉ"};
const char PY_mb_dao   []={"µ¶µ·µ¸µ¹µºµ»µ¼µ½µ¾µ¿µÀµÁØÖß¶àüâáë®ìâôî"};
const char PY_mb_de    []={"µÂµÃµÄµØï½"};
const char PY_mb_dei   []={"µÃ"};
const char PY_mb_deng  []={"³ÎµÅµÆµÇµÈµÉµÊµËàâáØê­íãïëô£"};
const char PY_mb_di    []={"µÄµÖµ×µØµÙµÚµÛµÜµİµÌµÍµÎµÏµĞµÑµÒµÓµÔµÕµŞÌáØµÙáÚ®ÚĞÛ¡Ûæİ¶àÖæ·èÜé¦êëíÆíÚíûïáôÆ÷¾"};
const char PY_mb_dia   []={"àÇ"};
const char PY_mb_dian  []={"µçµêµëµãµäµåµìµíµîµßµàµáµâµæµèµéÚçÛãáÛçèîäñ°ñ²ô¡õÚ"};
const char PY_mb_diao  []={"µõµóµôµöµ÷µïµğµñµòîöï¢õõöô"};
const char PY_mb_die   []={"µøµùµúµûµüµıµşÛìÜ¦Şéà©ëºğ¬ñóõŞöø"};
const char PY_mb_ding  []={"¶¡¶¢¶£¶¤¶¥¶¦¶§¶¨¶©Øêà¤çàëëíÖî®îúğÛñôôú"};
const char PY_mb_diu   []={"¶ªîû"};
const char PY_mb_dong  []={"¶«¶¬¶­¶®¶¯¶°¶±¶²¶³¶´ßËá´á¼ë±ëËëØíÏğ´"};
const char PY_mb_dou   []={"¶¹¶º¶»¶¼¶µ¶¶¶·¶¸İúñ¼ò½óû"};
const char PY_mb_du    []={"¶Ç¶È¶É¶¼¶½¶¾¶¿¶À¶Á¶Â¶Ã¶Ä¶Å¶Æ¶ÊÜ¶à½äÂèüë¹ó¼óÆ÷Ç÷ò"};
const char PY_mb_duan  []={"¶Ë¶Ì¶Í¶Î¶Ï¶Ğé²ìÑóı"};
const char PY_mb_dui   []={"¶Ñ¶Ò¶Ó¶Ôí¡í­íÔ"};
const char PY_mb_dun   []={"¶Ü¶Õ¶Ö¶×¶Ø¶Ù¶Ú¶Û¶İãçìÀí»íâíïïæõ»"};
const char PY_mb_duo   []={"¶à¶ä¶È¶Ş¶ß¶á¶â¶ã¶å¶æ¶ç¶è¶éÍÔßÍßáãõç¶îìñÖõâ"};
const char PY_mb_e     []={"°¢¶ê¶ë¶ì¶í¶î¶ï¶ğ¶ñ¶ò¶ó¶ô¶õ¶öÅ¶Ø¬ÚÌÛÑÜÃİ­İàßÀãµåíæ¹éîëñï°ïÉğÊò¦öù"};
const char PY_mb_ei    []={"ÚÀ"};
const char PY_mb_en    []={"¶÷İìŞô"};
const char PY_mb_er    []={"¶ş¶ø¶ù¶ú¶û¶ü¶ı·¡åÇçíîïğ¹öÜ"};
const char PY_mb_fa    []={"·¢·£·¤·¥·¦·§·¨·©ÛÒíÀ"};
const char PY_mb_fan   []={"·²·³·´·µ·¶···¸·¹·º·ª·«·¬·­·®·¯·°·±Ş¬ŞÀá¦èóìÜî²õì"};
const char PY_mb_fang  []={"·»·¼·½·¾·¿·À·Á·Â·Ã·Ä·ÅØÎÚúèÊîÕô³öĞ"};
const char PY_mb_fei   []={"·Æ·Ç·È·É·Ê·Ë·Ì·Í·Î·Ï·Ğ·ÑÜÀáôì³ã­åúç³äÇé¼êÚëèìéíÉïĞğòòãóõôäö­öî"};
const char PY_mb_fen   []={"·Ö·Ò·Ü·İ·Ş·ß·à·Ó·Ô·Õ·×·Ø·Ù·Ú·ÛÙÇå¯çãèûêÚö÷÷÷"};
const char PY_mb_feng  []={"·á·â·ã·ä·å·æ·ç·ï·è·é·ê·ë·ì·í·îÙºÛºİ×ßôããí¿"};
const char PY_mb_fo    []={"·ğ"};
const char PY_mb_fou   []={"·ñó¾"};
const char PY_mb_fu    []={"¸´·ğ¸µ¸¶¸·¸¸·ò·ó·ô·õ¸¾·ö·÷·ø·ù·ú·û·ü·ı·ş¸¡¸¢¸£¸¤¸¥¸¦¸§¸¨¸©¸ª¸«¸¬¸­¸®¸¯¸°¸±¸²¸³¸¹¸º¸»¸¼¸½¸¿¸ÀÙëÙìÚâÛ®Ü½ÜÀÜŞÜòİ³İÊŞÔß»á¥âöäæåõæÚæâç¦ç¨èõêçìğíÉíêíëî·ïûğ¥ò¶òİòğòóôïõÃõÆöÖöû"};
const char PY_mb_ga    []={"¸Á¸Â¼Ğ¿§Ù¤ŞÎæØæÙê¸îÅ"};
const char PY_mb_gai   []={"¸Ã¸Ä¸Å¸Æ¸Ç¸È½æØ¤ÚëÛòê®êàëÜ"};
const char PY_mb_gan   []={"¸É¸Ê¸Ë¸Ì¸Í¸Î¸Ï¸Ğ¸Ñ¸Ò¸ÓÛáÜÕŞÏß¦ãïäÆä÷ç¤éÏêºí·ğáôû"};
const char PY_mb_gang  []={"¸Ô¸Õ¸Ö¸×¸Ø¸Ù¸Ú¸Û¸Ü¿¸í°î¸óà"};
const char PY_mb_gao   []={"¸æ¸Ş¸ß¸à¸İ¸á¸â¸ã¸ä¸åØºÚ¾Û¬Ş»çÉéÀéÂê½ï¯"};
const char PY_mb_ge    []={"¸ö¸÷¸Ç¸ç÷Àëõ¸è¸é¸ê¸ë¸ì¸í¸î¸ï¸ğ¸ñ¸ò¸ó¸ô¸õºÏ¿©ØªØîÛÁÛÙÜªàÃæüë¡îşïÓñËò´ô´"};
const char PY_mb_gei   []={"¸ø"};
const char PY_mb_gen   []={"¸ù¸úØ¨İ¢ßçôŞ"};
const char PY_mb_geng  []={"¸û¸ü¸ı¸ş¹¡¹¢¹£¾±ßìâÙç®öá"};
const char PY_mb_gong  []={"¹¤¹²¹¥¹¦¹§¹«¹¬¹­¹¨¹©¹ª¹®¹¯¹°¹±ò¼ŞÃçîëÅö¡"};
const char PY_mb_gou   []={"¹³¹´¹µ¹¶¹»¹¸¹¹¹ºØşÚ¸¹·óôá¸åÜæÅçÃèÛêíì°óÑ÷¸"};
const char PY_mb_gu    []={"¹Ã¹À¹Á¹Â¹½¹¾¹¼¹¿¹Ä¹Å¹Æ¹Ç¹È¹É¹Ê¹Ë¹Ì¹Í¼ÖØÅÚ¬İÔáÄãéèôéïêôêöëûì±î­î¹îÜïÀğ³ğÀğóòÁôşõıöñ÷½"};
const char PY_mb_gua   []={"¹Î¹Ï¹Ğ¹Ñ¹Ò¹ÓØÔÚ´ßÉèéëÒğ»"};
const char PY_mb_guai  []={"¹Ô¹Õ¹ÖŞâ"};
const char PY_mb_guan  []={"¹Ø¹Ù¹Ú¹Û¹Ü¹İ¹Ş¹ß¹à¹áÂÚÙÄİ¸¹×ŞèäÊîÂğÙ÷¤"};
const char PY_mb_guang []={"¹â¹ã¹äßÛáîèæë×"};
const char PY_mb_gui   []={"¹å¹æ¹ç¹è¹é¹ê¹ë¹ì¹í¹î¹ğ¹ñ¹ò¹ó¹ô¹ïÈ²ØĞØÛâÑå³æ£èíêÁêĞğ§óşöÙ÷¬"};
const char PY_mb_gun   []={"¹õ¹ö¹÷ÙòçµíŞöç"};
const char PY_mb_guo   []={"¹ø¹ù¹ú¹û¹ü¹ıÎĞÙåÛöŞâßÃàşáÆâ£é¤ë½ï¾ñøòäòå"};
const char PY_mb_ha    []={"¹ş¸òîş"};
const char PY_mb_hai   []={"»¹¿Èº¢º£º¦º¤º¥º§º¡àËëÜõ°"};
const char PY_mb_han   []={"º¹ººº°º®º¬º­º¯º±º¨ºµº¶º·º¸º©ºªº«º²º³÷ıº´ÚõİÕŞşå«êÏìÊñüò¥òÀ"};
const char PY_mb_hang  []={"ĞĞº»º¼º½¿ÔÏïãìç¬ñş"};
const char PY_mb_hao   []={"ºÂºÃºÄºÅê»ğ©ºÁºÆå°¸äº¾º¿ºÀºÑİïŞ¶àÆàãå©ò«òº"};
const char PY_mb_he    []={"ºÇºÈºÉºÊºËºÌºÍºÎºÏºÓºĞºÑºÒºÔºÕºØºÖº×ÏÅÚ­ÛÀÛÖàÀãØæüêÂîÁò¢òÂôç"};
const char PY_mb_hei   []={"ºÚºÙ"};
const char PY_mb_hen   []={"ºÛºÜºİºŞ"};
const char PY_mb_heng  []={"ºßºàºáºâºãŞ¿çñèì"};
const char PY_mb_hong  []={"ºìºäºåºæºçºèºéºêºëÙäÙêÚ§İ¦Ş®Ş°ãÈãü"};
const char PY_mb_hou   []={"ºóºíºîºïºğºñºòÜ©ááåËğúóóô×ö×÷¿"};
const char PY_mb_hu    []={"»¤»¥»¦»§ºËºôºõºöº÷ºøºùºúºû»¢ºüºıºş»¡»£Ùüßüàñá²â©âïã±ä°äïçúéÎéõì²ìÃìÎìæìèìïğ­ğÀğÉğ×ò®óËõ­õú÷½"};
const char PY_mb_hua   []={"»¨»ª»«»¬»©»­»®»¯»°æèèëí¹îü"};
const char PY_mb_huai  []={"»µ»±»²»³»´õ×"};
const char PY_mb_huan  []={"»¶»·»¸»¹»º»»»¼»½»¾»À»Á»Â»Ã÷ßä½»¿Û¨Û¼ÛùİÈß§à÷âµä¡äñå¾åÕçÙïÌöé"};
const char PY_mb_huang []={"»Î»Ä»Å»Æ»Ç»È»É»Ê»Ë»Ì»Í»Ï»Ğ»ÑÚòáåäÒäêåØè«ëÁñ¥ó¨óòöü"};
const char PY_mb_hui   []={"»á»Ø»Ù»Ú»Ò»Ó»Ô»Õ»Ö»×»Û»Ü»İ»Ş»ß»à»â»ã»ä»å»æåçÀ£Ú¶ÜîÜöŞ¥ßÔßÜà¹ãÄä§ä«çÀèíêÍí£ò³ó³÷â"};
const char PY_mb_hun   []={"»ç»è»é»ê»ë»ìÚ»âÆãÔäãçõ"};
const char PY_mb_huo   []={"ºÍ»í»î»ï»ğ»ñ»ò»ó»ô»õ»öØåŞ½ß«àëâ·îØïÁïìñëó¶"};
const char PY_mb_ji    []={"¼Æ¼Ç¸ø¼¼»÷»ù¼¸¼¹¼º»ø¼®¼¯¼°¼±¼²¼³¼´¼µ¼¶¼·¼»¼È¼É¼Ê¼½¼¾¼¿¼À¼Á»ú»û»ü»ı¼¡¼¢¼£¼¤¼¥¼¦¼§¼¨¼©¼ª¼«¼¬»ş¼­¼Â¼Ã¼Ä¼Å¼Ë¼Ì¼Í½åÆæÏµØ¢Ø½ØÀØŞÙ¥ÙÊÛÔÜ¸ÜÁÜùİ½İğŞªŞáß´ßÒßâßóá§áÕä©åæåìæ÷çÜçáé®éêêªê«êåêéê÷ì´í¶î¿ïúğ¢ñ¤ò±óÅóÇôßõÒõÕö«öİöê÷Ù÷ä"};
const char PY_mb_jia   []={"¼Ò¼Ó¼Î¼Ğ¼Ñ¼Ô¼Õ¼Ö¼×¼Ø¼Ù¼Ú¼Û¼Ü¼İ¼Ş¼ÏÇÑØÅÙ¤Û£İçáµä¤åÈçìê©ëÎí¢îòîşïØğèğıñÊòÌóÕôÂõÊ"};
const char PY_mb_jian  []={"½¨¼û¼ş¼ò½¡¼õ¼ß¼ö¼à¼ñ¼ó¼ô¼á¼â¼ä¼å¼æ¼ç¼è¼é¼ê¼ë¼ì¼í¼î¼ï¼ğ¼ã¼÷¼ø¼ù¼ú¼ü¼ı½¢½£½¤½¥½¦½§ÙÔÚÉÚÙÚÚİÑİóŞöàîäÕå¿åÀçÌèÅé¥ê§ê¯êğêùë¦ëìíúïµğÏñĞóÈôåõÂõİöä÷µ"};
const char PY_mb_jiang []={"½²ºç½©½ª½«½¬½­½®½¯½°½±½³½´½µÇ¿Üüä®ç­çÖêñíäñğôİôø"};
const char PY_mb_jiao  []={"½Ğ½Ï¾õ½ÇĞ£½¶½·½¸½¹½º½»½¼½½½¾½¿½À½Á½Â½Ã½Ä½Å½Æ½È½É½Ê½Ë½Ì½Í½Î½ÑÙ®ÙÕÜ´ÜúŞØàİá½áèæ¯ë¸ğ¨ğÔòÔõ´õÓöŞ"};
const char PY_mb_jie   []={"½à½á½â½ã½ä½Ò½Ü½Ó½Ô½ç½è½é½İ½Ş½Õ½Ö½×½Ø½Ù½Ú½Û½ß½å½æ½ê½ë½ìÙÊÚ¦ÚµÚàŞ×à®àµæ¼æİèîíÙïÇğÜò¡ò»ôÉöÚ÷º"};
const char PY_mb_jin   []={"½í¾¡½î½ï½ğ½ñ½ò½ô½õ½ö½÷½ø½ù½ú½û½ü½ı½ş¾¢½óÚáİ£İÀàäâËâÛæ¡çÆèªéÈêáêîîÄñÆñæ"};
const char PY_mb_jing  []={"¾©¾ª¾«¾­¾®¾¦¾§¾°¾»¾±¾²¾³¾´¾¯¾µ¾¶¾¹¾º¾¢¾£¾¤¾¥¾¨¾¬¾·¾¸ØÙÙÓÚåÚêİ¼â°ã½ãşåÉåòæºëÂëÖëæìºö¦"};
const char PY_mb_jiong []={"¾¼¾½ØçåÄìç"};
const char PY_mb_jiu   []={"¾Å¾Í¾È¾¾¾¿¾À¾Á¾Â¾Ã¾Ä¾Æ¾É¾Ê¾Ë¾Ì¾Î¾ÇÙÖà±ãÎèÑèêğ¯ğÕôñ÷İ"};
const char PY_mb_ju    []={"¾Ş¾ß¾à¾ã¾ä¾å³µ¹ñ¾ç¾Ó¾Ô¾Õ¾Ö¾×¾Ø¾Ù¾Ú¾Û¾Ü¾İ¾á¾â¾æ¾Ï¾Ğ¾Ñ¾ÒÙÆÚªÜÄÜÚÜìŞäåáåğè¢èÛé§é°é·éÙêøì«îÒï¸ñÀñÕôòõ¶õáö´öÂöÄ÷¶"};
const char PY_mb_juan  []={"¾ì¾í¾è¾é¾ê¾ë¾îÈ¦Û²áúä¸èğîÃïÃïÔöÁ"};
const char PY_mb_jue   []={"¾ö¾÷¾ø¾õ½Ç¾ò¾ó½À½Å¾ï¾ğ¾ñ¾ôØÊØãÚÜÛÇÜ¥Ş§àÙáÈâ±æŞçåèöéÓìßïãõêõû"};
const char PY_mb_jun   []={"¾ü¾ı¾ù¾ú¾û¾ş¿¡¿¢¿£¿¤¿¥¹êŞÜñäóŞ÷å"};
const char PY_mb_ka    []={"¿¨¿¦¿§¿©ØûßÇëÌ"};
const char PY_mb_kai   []={"¿ª¿«¿¬¿­¿®ØÜÛîİÜâéâıîøï´ïÇ"};
const char PY_mb_kan   []={"¿´¿¯¿°¿±¿²¿³Ù©íèî«ÛÉİ¨ãÛ¼÷ê¬"};
const char PY_mb_kang  []={"¿µ¿¶¿·¿¸¿¹¿º¿»ØøãÊîÖ"};
const char PY_mb_kao   []={"¿¼¿¿¿½¿¾èàêûîíåê"};
const char PY_mb_ke    []={"¿É¿Ê¿Ë¿Æ¿Ì¿Í¿Îà¾¿À¿Á¿Â¿Ã¿Ä¿Å¿Ç¿Èã¡òòá³äÛïıæìç¼çæéğë´î§îİîşºÇï¾ğâñ½ò¤òÂ÷Á"};
const char PY_mb_ken   []={"¿Ï¿Ğ¿Ñ¿ÒñÌ"};
const char PY_mb_keng  []={"¿Ó¿Ôï¬ëÖîï"};
const char PY_mb_kong  []={"¿Õ¿Ö¿×¿ØÙÅáÇóí"};
const char PY_mb_kou   []={"¿Ù¿Ú¿Û¿ÜÜÒŞ¢ßµíîóØ"};
const char PY_mb_ku    []={"¿İ¿Ş¿ß¿à¿á¿â¿ãç«÷¼ØÚÜ¥à·"};
const char PY_mb_kua   []={"¿ä¿å¿æ¿ç¿èÙ¨ï¾"};
const char PY_mb_kuai  []={"»á¿é¿ê¿ë¿ìØáÛ¦ßàáöëÚ"};
const char PY_mb_kuan  []={"¿í¿î÷Å"};
const char PY_mb_kuang []={"¿ö¿ï¿ğ¿ñ¿ò¿ó¿ô¿õÚ²Ú¿Ú÷ÛÛŞÅßÑæşêÜ"};
const char PY_mb_kui   []={"¿÷¿ø¿ù¿ú¿û¿ü¿ı¿şÀ¡À¢À£Ø¸ØÑåÓî¥õÍÙçÚóİŞŞñà­à°ã¦ã´êÒñùòñóñ"};
const char PY_mb_kun   []={"À¤À¥À¦À§ã§çûï¿õ«öïãÍ÷Õ"};
const char PY_mb_kuo   []={"À¨À©ÀªÀ«òÒ"};
const char PY_mb_la    []={"À¬À­À®À¯À°À±À²ÂäØİååê¹íÇğø"};
const char PY_mb_lai   []={"À³À´ÀµáÁáâäµäşêãíùñ®ô¥ïª"};
const char PY_mb_lan   []={"À¶À·À¸À¹ÀºÀ»À¼À½À¾À¿ÀÀÀÁÀÂÀÃÀÄá°äíé­ìµïçñÜî½"};
const char PY_mb_lang  []={"ÀÉÀÊÀËÀÅÀÆÀÇÀÈà¥ãÏòëï¶İõïüİ¹"};
const char PY_mb_lao   []={"ÀÌÀÍÀÎÀÏÀĞÀÑÀÒÀÓÀÔÂäÂçßëáÀõ²èáîîï©ğìñì"};
const char PY_mb_le    []={"ÀÕÀÖÁËØìß·ãî÷¦"};
const char PY_mb_lei   []={"ÀÛÀÕÀ×ÀØÀÙÀÚÀÜÀİÀŞÀßÀàÀáÙúÚ³àÏæĞçĞéÛñçõª"};
const char PY_mb_leng  []={"ÀâÀãÀäÜ¨ã¶"};
const char PY_mb_li    []={"ÀûÁ¦ÀúÀ÷Á¢Á£ÀñÁ¤ÀôÀíÀîÀïÀåÀøÀöÀæÀçÁ¥ÀèÀéÀëÀìÀğÀõÀùÀòÀóÀêÀüÀıÀşÁ¡Á§Á¨ØªÙ³ÙµÛªÛŞÜÂİ°İñŞ¼ß¿à¦à¬áûäàå¢åÎæ²æËæêçÊèÀèİéöìåíÂíÇîºî¾ï®ğ¿ğİğßòÃòÛó»óÒóöôÏõ·õÈö¨öâ÷¯÷ó"};
const char PY_mb_lia   []={"Á©"};
const char PY_mb_lian  []={"ÁªÁ«Á¬Á®Á¯Á°Á±Á²Á³Á´ÁµÁ¶Á·äòÁ­å¥çöé¬ŞÆéçİüì¡ñÍñÏó¹öã"};
const char PY_mb_liang []={"Á½ÁÁÁ©Á¸Á¹ÁºÁ»Á¼Á¾Á¿ÁÀÁÂÜ®İ¹é£õÔ÷Ë"};
const char PY_mb_liao  []={"ÁËÁÃÁÏÁÄÁÅÁÆÁÇÁÈÁÉÁÊÁÌÁÍÁÎŞ¤ŞÍàÚâ²å¼çÔîÉğÓ"};
const char PY_mb_lie   []={"ÁĞÁÑÁÒÁÓä£ÁÔÙıÛøŞæßÖôóõñ÷à"};
const char PY_mb_lin   []={"ÁÙÁÚÁŞÁàÁÕÁÖÁ×ÁØÁÛÁÜÁİÁßİşßøá×âŞãÁåàéİê¥ì¢î¬ôÔõï÷ë"};
const char PY_mb_ling  []={"ÁîÁéÁíÀâÁáÁâÁãÁäÁåÁæÁçÁèÁêÁëñöÁìÛ¹ÜßßÊàòãöç±èÚèùê²òÈôáöì"};
const char PY_mb_liu   []={"ÁõÁùÁïÁğÁñÁòÁóÁôÁöÁ÷ÁøÂµÂ½ä¯åŞæòç¸ì¼ìÖï³ïÖğÒöÌ"};
const char PY_mb_lo    []={"¿©"}; 
const char PY_mb_long  []={"ÁúÅªÁûÁüÁıÁşÂ¡Â¢Â£Â¤ÛâÜ×ãñççèĞëÊíÃñª"};
const char PY_mb_lou   []={"Â¥Â¦Â§Â¨Â©ÂªÂ¶ÙÍİäà¶áĞïÎğüñïò÷÷Ã"};
const char PY_mb_lu    []={"ÁùÂ«Â¬Â­Â®Â¯Â°Â±Â²Â³Â´ÂµÂ¶Â·Â¸Â¹ÂºÂ»Â¼Â½Â¾ÂÌÛäß£ààãòäËäõåÖè´èÓéÖéñéûê¤êÚëªëÍïåğµğØóüôµöÔ"};
const char PY_mb_lv    []={"ÂËÂÊÂÌÂÀÂÁÂÂÂÃÂÄÂÅÂÆÂÇÂÈÂÉÂ¿ñÚÙÍŞÛãÌéµëöïù"}; 
const char PY_mb_luan  []={"ÂÒÂÏÂÍÂÎÂĞÂÑ"};
const char PY_mb_lue   []={"ÂÓÂÔï²"};
const char PY_mb_lun   []={"ÂØÂÕÂÖÂ×ÂÙÂÚÂÛàğ"};
const char PY_mb_luo   []={"ÂäÂŞ¸õ¿©ÀÓÂÜÂİÂßÂàÂáÂâÂãÂåÂæÂçÙÀÙùÜıŞÛŞûâ¤ãøäğçóé¡ëáíÑïİñ§öÃ"};
const char PY_mb_m     []={"ß¼"};  
const char PY_mb_ma    []={"ÂèÂéÂêÂëÂìÂíÂîÂïÂğÄ¦Ä¨ßéáïæÖè¿ó¡"};
const char PY_mb_mai   []={"ÂñÂ÷ÂøÂùÂúÂûÂüÂıÂşÃ¡Ü¬á£çÏì×ïÜò©òı÷©÷´"};
const char PY_mb_man   []={"ÂùÂøÂ÷ÂúÂüÃ¡ÂıÂşÂû"};
const char PY_mb_mang  []={"Ã¢Ã£Ã¤Ã¥Ã¦Ã§ÚøäİíËòş"};
const char PY_mb_mao   []={"Ã¨Ã©ÃªÃ«Ã¬÷ÖÃ®Ã¯Ã°Ã±Ã²Ã³ÙóÃ­Üâá¹ã÷è£êÄêóë£ì¸í®î¦òúó±"};
const char PY_mb_me    []={"Ã´"};
const char PY_mb_mei   []={"Ã¿ÃÃÃÀÃµÃ¶ÃÁÃÂñÇ÷ÈÃ·Ã¸Ã¹ÃºÃ»Ã¼Ã½Ã¾ÃÄİ®áÒâ­ä¼äØé¹ïÑğÌ"};
const char PY_mb_men   []={"ÃÅÃÆÃÇŞÑìËí¯îÍ"};
const char PY_mb_meng  []={"ÃÈÃÎÃÉÃÊÃËÃÌÃÍÃÏÛÂİùŞ«ãÂëüíæòµòìó·ô»ô¿"};
const char PY_mb_mi    []={"ÃĞÃÑÃÒÃÓÃÔÃÕÃÖÃ×ÃØÃÙÃÚÃÛÃÜ÷çÚ×ÃİØÂÚ¢ŞÂßäà×â¨ãèåµåôæùëßìòôÍôé÷ã"};
const char PY_mb_mian  []={"ÃæÃŞÃßÃàÃáÃâÃãÃäÃåãæäÅäÏå²ëïíí"};
const char PY_mb_miao  []={"ÃçÃèÃéÃêÃëÃìÃíÃîß÷åãç¿çÑèÂíµíğğÅ"};
const char PY_mb_mie   []={"ÃïÃğØ¿ßãóúóº"};
const char PY_mb_min   []={"ÃñÃòÃóÃôÃõÃöÜåáºãÉãıçÅçäçëíªö¼÷ª"};
const char PY_mb_ming  []={"Ã÷ÃøÃùÃúÃûÃüÚ¤ÜøäéêÔî¨õ¤"};
const char PY_mb_miu   []={"ÃıçÑ"};
const char PY_mb_mo    []={"ÂöÃ»ÃşÄ¡Ä¢Ä£Ä¤Ä¥Ä¦Ä§Ä¨Ä©ÄªÄ«Ä¬Ä­Ä®Ä¯Ä°÷áÍòÚÓÜÔİëâÉæÆéâïÒï÷ñ¢ñòõöõø"};
const char PY_mb_mou   []={"Ä±Ä²Ä³Ù°ßèçÑíøòÖöÊ"};
const char PY_mb_mu    []={"Ä¾Ä¿ÄÀÄ£Ä²Ä´ÄµÄ¶Ä·Ä¸Ä¹ÄºÄ»Ä¼Ä½ÄÁÄÂÜÙãåØïÛéë¤îâ"};
const char PY_mb_na    []={"ÄÃÄÄÄÅÄÆÄÇÄÈÄÉŞàëÇïÕñÄ"};
const char PY_mb_nai   []={"ÄÊÄËÄÌÄÍÄÎØ¾Ù¦ÜµİÁèÍ"};
const char PY_mb_nan   []={"ÄÏÄĞÄÑà«àïéªëîòïôö"};
const char PY_mb_nang  []={"ÄÒàìâÎß­êÙ"};
const char PY_mb_nao   []={"ÄÓÄÔÄÕÄÖÄ×Ø«ÛñßÎâ®è§íĞîóòÍ"};
const char PY_mb_ne    []={"ÄÄÄØÚ«"};
const char PY_mb_nei   []={"ÄÚÄÙ"};
const char PY_mb_nen   []={"ÄÛí¥"};
const char PY_mb_neng  []={"ÄÜ"};
const char PY_mb_ng    []={"àÅ"}; 
const char PY_mb_ni    []={"ÄãÄØÄâÄáÄİÄŞÄßÄàÄäÄåÄæÄçÙ£Ûèâ¥âõêÇì»ìòí«íşîêöò"};
const char PY_mb_nian  []={"ÄèÄéÄêÄëÄìÄíÄîØ¥Ûşéığ¤öÓöó"};
const char PY_mb_niang []={"ÄïÄğ"};
const char PY_mb_niao  []={"ÄñÄòëåôÁÜàæÕ"};
const char PY_mb_nie   []={"ÄóÄôÄõÄöÄ÷ÄøÄùõæŞÁà¿Ø¿Úíò¨ô«"};
const char PY_mb_nin   []={"Äú"};
const char PY_mb_ning  []={"ÄûÄüÄıÄşÅ¡Å¢ØúßÌå¸ñ÷"};
const char PY_mb_niu   []={"Å£Å¤Å¥Å¦ŞÖæ¤áğâî"};
const char PY_mb_nong  []={"Å§Å¨Å©ÅªÙ¯ßæ"};
const char PY_mb_nou   []={"ññ"};
const char PY_mb_nu    []={"Å«Å¬Å­åóæÀæÛæå"};
const char PY_mb_nuan  []={"Å¯"};
const char PY_mb_nue   []={"Å±Å°"};
const char PY_mb_nuo   []={"ÄÈÅ²Å³Å´ÅµÙĞŞùßöï»"};
const char PY_mb_nv    []={"Å®í¤îÏô¬"};
const char PY_mb_o     []={"Å¶à¸àŞ"};
const char PY_mb_ou    []={"Å·Å¸Å¹ÅºÅ»Å¼Å½ÇøÚ©âæê±ñî"};
const char PY_mb_pa    []={"°Ç°ÒÅ¾Å¿ÅÀÅÁÅÂÅÃİâèËóá"};
const char PY_mb_pai   []={"ÅÄÅÅÅÆÅÇÅÈÅÉÆÈÙ½İåßß"};
const char PY_mb_pan   []={"·¬ÅÊÅËÅÌÅÍÅÎÅÏÅĞÅÑó´õçÅÖŞÕãÜãİãúêÚñÈñá"};
const char PY_mb_pang  []={"°ò°õ°÷ÅÒÅÓÅÔÅÕÅÖáİäèó¦åÌ"};
const char PY_mb_pao   []={"Å×ÅØÅÙÅÚÅÛÅÜÅİáóâÒğåëãŞË"};
const char PY_mb_pei   []={"ÅŞÅßÅàÅáÅâÅãÅäÅåÅæàÎö¬àúì·ïÂõ¬"};
const char PY_mb_pen   []={"ÅçÅèäÔ"};
const char PY_mb_peng  []={"ÅõÅöÅéÅêÅëÅìÅíÅîÅïÅğÅñÅòÅóÅôâñÜ¡àØó²"};
const char PY_mb_pi    []={"±Ù·ñÅ÷ÅøÅùÅúÅûÅüÅıÅşÆ¡Æ¢Æ£Æ¤Æ¥Æ¦Æ§Ø§Æ¨Æ©ñ±õùØòÚéÚğÚüÛ¯ÛÜÛıÜ±ÜÅß¨àèâÏäÄæÇç¢èÁê¶î¢î¼îëñÔñâò·òç"};
const char PY_mb_pian  []={"±â±ãÆªÆ«Æ¬Æ­ÚÒæéçÂêúëİôæõä"};
const char PY_mb_piao  []={"Æ®Æ¯Æ°Æ±ÆÓØâæÎçÎî©àÑæôéèóª"};
const char PY_mb_pie   []={"Æ²Æ³Ø¯ÜÖë­"};
const char PY_mb_pin   []={"Æ´ÆµÆ¶Æ·Æ¸æ°æÉé¯êòò­"};
const char PY_mb_ping  []={"·ëÆ¹ÆºÆ»Æ¼Æ½Æ¾Æ¿ÆÀÆÁÙ·æ³èÒöÒ"};
const char PY_mb_po    []={"²´·±ÆÂÆÃÆÄÆÅÆÆÆÇÆÈÆÉÆÓØÏÚéÛ¶çêê·ë¶îÇîŞğ«óÍ"};
const char PY_mb_pou   []={"ÆÊÙöŞå"};
const char PY_mb_pu    []={"ÆÕ±¤±©¸¬ÆËÆÌÆÍÆÎÆÏÆĞÆÑÆÒÆÓÆÔÆÖÆ×ÆØÆÙÙéàÛäßõëå§è±ë«ïäïè"};
const char PY_mb_qi    []={"ÆßÆğÆŞÆòÆóÆô»ü¼©ÆÚÆÛÆÜÆİÆàÆáÆâÆãÆäÆåÆæÆçÆèÆéÆêÆëÆìÆíáªÆîÆïÆñç÷çùè½ÆõÆöÆ÷ÆøÆùÆúÆûÆüÆıØ½ì÷í¬õè÷¢÷èØÁÙ¹ÛßÜ»ÜÎÜùİÂİİä¿æëç²êÈŞ­èçéÊì¥àÒá¨ãàíÓñıòÓòàôëôì"};
const char PY_mb_qia   []={"¿¨ÆşÇ¡Ç¢İÖñÊ÷Ä"};
const char PY_mb_qian  []={"Ç£Ç¤Ç¥Ç¦Ç§Ç¨Ç©ÇªÇ«Ç¬Ç­Ç®Ç¯Ç°Ç±Ç²Ç³Ç´ÇµÇ¶Ç·Ç¸ÏËÙ»ÙİÚäÜ·ÜÍÜçİ¡Şçá©ã¥ã»å¹åºå½ç×èıêùëÉí©îÔò¯óéôÇ"};
const char PY_mb_qiang []={"Ç¹ÇºÇ»Ç¼Ç½Ç¾Ç¿ÇÀõÄãŞê¨ìÁïÏïêãÜñßæÍéÉòŞôÇ"};
const char PY_mb_qiao  []={"¿ÇÇÁÇÂÇÃÇÄÇÅÇÆÇÇÇÈÇÉÇÊÇËÇÌÇÍÇÎÇÏÈ¸Ú½ÚÛÜñá½ã¾éÔõÎ÷³çØØäã¸íÍï¢"};
const char PY_mb_qie   []={"ÇĞÇÑÇÒÇÓÇÔÙ¤ã«ã»æªôòÛ§êüïÆóæ"};
const char PY_mb_qin   []={"ÇÕÇÖÇ×ÇØÇÙÇÚÇÛÇÜÇİÇŞÇßÜËŞìôÀßÄàºàßâÛéÕï·ñæñûòû"};
const char PY_mb_qing  []={"Ç×ÇàÇáÇâÇãÇäÇåÇæÇçÇèÇéÇêÇëÇìíàÜÜàõéÑïºòßóÀóäôìö¥öë÷ô"};
const char PY_mb_qiong []={"ÇíÇîñ·òËÚöÜäóÌõ¼öÆ"};
const char PY_mb_qiu   []={"³ğ¹êÇïÇğÇñÇòÇóÇôÇõÇöÙ´åÏôÃôÜåÙÛÏáìäĞé±êäò°òÇòøöú"};
const char PY_mb_qu    []={"Ç÷ÇøÇùÇúÇûÇüÇıÇşÈ¡È¢È£È¤È¥òĞ÷ñĞçÚ°Û¾ÛÉÜÄŞ¡Ş¾á«áéãÖè³êïë¬ëÔìîíáğ¶ñ³ó½ôğöÄ"};
const char PY_mb_quan  []={"È¦È§È¨È©ÈªÈ«È¬È­È®È¯È°Ú¹Üõòé÷Üáëãªç¹éúî°îıóÜ"};
const char PY_mb_que   []={"È±È²È³È´ÈµÈ¶È·È¸ã×ãÚí¨"};
const char PY_mb_qui   []={"÷ü"};  
const char PY_mb_qun   []={"È¹ÈºåÒ÷å"};
const char PY_mb_ran   []={"È»È¼È½È¾ÜÛòÅ÷×"};
const char PY_mb_rang  []={"È¿ÈÀÈÁÈÂÈÃìüğ¦"};
const char PY_mb_rao   []={"ÈÄÈÅÈÆÜéæ¬èã"};
const char PY_mb_re    []={"ÈÇÈÈßö"};
const char PY_mb_ren   []={"ÈÉÈÊÈËÈÌÈÍÈÎÈÏÈĞÈÑÈÒïşØéØğÜóİØâ¿éíñÅ"};
const char PY_mb_reng  []={"ÈÓÈÔ"};
const char PY_mb_ri    []={"ÈÕ"};
const char PY_mb_rong  []={"ÈÖÈ×ÈØÈÙÈÚÈÛÈÜÈİÈŞÈßáÉáõéÅëÀòî"};
const char PY_mb_rou   []={"ÈàÈáÈâôÛõå÷·"};
const char PY_mb_ru    []={"ÈãÈäÈåÈæÈçÈèÈéÈêÈëå¦ÈìäáİêàéŞ¸ä²çÈï¨ñàò¬"};
const char PY_mb_ruan  []={"ÈíÈîëÃ"};
const char PY_mb_rui   []={"ÈïÈğÈñÜÇî£èÄŞ¨ò¸"};
const char PY_mb_run   []={"ÈòÈó"};
const char PY_mb_ruo   []={"ÈôÈõÙ¼óè"};
const char PY_mb_sa    []={"ÈöÈ÷ÈøØ¦ØíìªëÛ"};
const char PY_mb_sai   []={"ÈùÈúÈûÈüàç"};
const char PY_mb_san   []={"ÈıÈşÉ¡É¢âÌë§ôÖ"};
const char PY_mb_sang  []={"É£É¤É¥Şúíßòª"};
const char PY_mb_sao   []={"É¦É§É¨É©ëığşÜ£çÒöş"};
const char PY_mb_se    []={"ÈûÉªÉ«É¬ØÄï¤ğ£"};
const char PY_mb_sen   []={"É­"};
const char PY_mb_seng  []={"É®"};
const char PY_mb_sha   []={"É¯É°É±É²É³É´ÉµÉ¶É·É¼ÏÃğğôÄö®öèßşì¦ï¡"};
const char PY_mb_shai  []={"É«É¸É¹"};
const char PY_mb_shan  []={"²ôµ¥ÉºÉ»É¼É½É¾É¿ÉÀÉÁÉÂÉÃÉÄÉÅÉÆÉÇÉÈÉÉÕ¤Ú¨ğŞô®óµõÇ÷­ØßÛ·ÛïÜÏáêäúæ©æÓæóëşìøîÌ÷Ô"};
const char PY_mb_shang []={"ÉÊÉËÉÌÉÍÉÎÉÏÉĞÉÑç´éäõüÛğìØ"};
const char PY_mb_shao  []={"ÇÊÉÒÉÓÉÔÉÕÉÖÉ×ÉØÉÙÉÚÉÛÉÜÛ¿Üæô¹äûè¼òÙóâ"};
const char PY_mb_she   []={"ÉİÉŞÉßÉàÉáÉâÉãÉäÉåÉæÉçÉè÷êÕÛØÇÙÜŞéâ¦äÜì¨î´îè"};
const char PY_mb_shei  []={"Ë­"}; 
const char PY_mb_shen  []={"Ê²²ÎÉéÉêÉëÉìÉíÉîÉïÉğÉñÉòÉóÉôÉõÉöÉ÷ÉøÚ·ÚÅİ·İØßÓäÉé©ëÏïòò×"};
const char PY_mb_sheng []={"³ËÉùÉúÉûÉüÉıÉşÊ¡Ê¢Ê£Ê¤Ê¥óÏáÓäÅêÉíò"};
const char PY_mb_shi   []={"ÊÇÊÂ³×Ê¦Ê®Ê¯Ê§Ê¨Ê©ÊªÊ«Ê¬Ê­Ê°Ê±Ê²Ê³Ê´ÊµÊ¶Ê·Ê¸Ê¹ÊºÊ»Ê¼Ê½Ê¾Ê¿ÊÀÊÁÊÃÊÄÊÅÊÆÊÈÊÉÊÊÊËÊÌÊÍÊÎÊÏÊĞÊÑÊÒÊÓÊÔËÆß±óÂÖ³ÖÅÚÖÛõİªİéâ»éøêÛìÂìêîæîèó§óßõ§õ¹öåöõ"};
const char PY_mb_shou  []={"ÊÕÊÖÊ×ÊØÊÙÊÚÊÛÊÜÊİÊŞŞĞá÷ç·ô¼"};
const char PY_mb_shu   []={"ÊßÊàÊáÊâÊãÊäÊåÊæÊçÊèÊéÊêÊëÊìÊíÊîÊïÊğÊñÊòÊóÊôÊõÊöÊ÷ÊøÊùÊúÊûÊüÊıÊşË¡Ù¿ÛÓãğäøæ­Ø­İÄŞóç£ë¨ëòì¯ïíïøñâ"};
const char PY_mb_shua  []={"Ë¢Ë£à§"};
const char PY_mb_shuai []={"ÂÊË¤Ë¥Ë¦Ë§ó°"};
const char PY_mb_shuan []={"Ë¨Ë©ãÅäÌ"};
const char PY_mb_shuang[]={"ËªË«Ë¬ãñæ×"};
const char PY_mb_shui  []={"Ë®Ë¯Ë°Ëµãß"};
const char PY_mb_shun  []={"Ë±Ë²Ë³Ë´"};
const char PY_mb_shuo  []={"ÊıËµË¶Ë·Ë¸İôŞ÷åùéÃîå"};
const char PY_mb_si    []={"Ë¹ËºË»Ë¼Ë½Ë¾Ë¿ËÀËÁËÂËÃËÄËÅËÆËÇËÈØËßĞÙ¹ÙîÛÌâ»ãáãôäùæ¦æáçÁìëïÈğ¸ñêòÏóÓ"};
const char PY_mb_song  []={"ËÉËÊËËËÌËÍËÎËÏËĞáÔâìã¤äÁñµáÂİ¿Ú¡"};
const char PY_mb_sou   []={"ËÑËÒËÓËÔÛÅà²âÈäÑì¬î¤ïËòôàÕŞ´"};
const char PY_mb_su    []={"ËÕËÖË×ËØËÙËÚËÛËÜËİËŞËßËàËõÙíãºä³óùöÕÚÕİøà¼ö¢"};
const char PY_mb_suan  []={"ËáËâËãâ¡"};
const char PY_mb_sui   []={"ËäËêËçËåËæËèËîËìËéËíËë"};
const char PY_mb_sun   []={"ËïËğËñ"};
const char PY_mb_suo   []={"ËòËóËôËõËöË÷ËøËùßïàÂàÊæ¶É¯èøêıíüôÈ"};
const char PY_mb_ta    []={"ËúËûËüËıËşÌ¡Ì¢í³Ì£Ì¤ÍØãËåİé½îèõÁäâ÷£äğ"};
const char PY_mb_tai   []={"Ì¥Ì¦Ì§Ì¨Ì©ÌªÌ«Ì¬Ì­õÌÛ¢Ş·ææëÄìÆîÑöØ"};
const char PY_mb_tan   []={"µ¯Ì®Ì¯Ì°Ì±Ì²Ì³Ì´ÌµÌ¶Ì·Ì¸Ì¹ÌºÌ»Ì¼Ì½Ì¾Ì¿ñûÛ°å£ê¼êæìşîãïÄïâ"};
const char PY_mb_tang  []={"ÌÀÌÁÌÂÌÃÌÄÌÅÌÆÌÇÌÈÌÉÌÊÌËÌÌÙÎâ¼äçè©éÌîõó«ï¦ïÛñíó¥ôÊõ±àû"};
const char PY_mb_tao   []={"ÌÍÌÎÌÏÌĞÌÑÌÒÌÓÌÔÌÕÌÖÌ×ß¶ßû÷Òä¬èºìâØ»"};
const char PY_mb_te    []={"ÌØß¯ìıï«"};
const char PY_mb_teng  []={"ÌÙÌÚÌÛëøÌÜ"};
const char PY_mb_ti    []={"ÌİÌŞÌßÌàÌáÌâÌãÌäÌåÌæÌçÌèÌéÌêÌëÙÃã©ç¾ÜèåÑç°ğÃñÓõ®"};
const char PY_mb_tian  []={"ÌìÌíÌîÌïÌğÌñÌòÌóéåŞİãÃãÙî±îäï»"};
const char PY_mb_tiao  []={"µ÷ÌôÌõÌöÌ÷ÌøÙ¬÷ØÜæìöï¢ñ»òèóÔôĞö¶öæ"};
const char PY_mb_tie   []={"ÌùÌúÌû÷Ñï°İÆ"};
const char PY_mb_ting  []={"ÌüÌıÌşÍ¡Í¢Í£Í¤Í¥Í¦Í§ÜğİãæÃîúòÑöªèè"};
const char PY_mb_tong  []={"Í©Í«Í¬Í­Í®Í¯Í°Í±Í²Í³Í´Ù¡Ù×ÜíâúäüÍªÙÚÛíàÌá¼íÅ"};
const char PY_mb_tou   []={"ÍµÍ¶Í·Í¸÷»î×Ùï"};
const char PY_mb_tu    []={"Í¹ÍºÍ»Í¼Í½Í¾Í¿ÍÀÍÁÍÂÍÃÜ¢İ±İËîÊõ©"};
const char PY_mb_tuan  []={"ÍÄÍÅŞÒåèî¶"};
const char PY_mb_tui   []={"ÍÆÍÇÍÈÍÉÍÊÍËìÕ"};
const char PY_mb_tun   []={"¶ÚÍÊÍÌÍÍÍÎâ½ëàÙÛêÕ"};
const char PY_mb_tuo   []={"ËµÍÏÍØÍĞÍÑÍÒÍÓÍÔÍÕÍÖÍ×ÍÙõÉØ±Ù¢ÛçãûèØèŞéÒíÈîèö¾óêõ¢âÕ"};
const char PY_mb_wa    []={"ÍÚÍÛÍÜÍİÍŞÍßÍàØôæ´ëğ"};
const char PY_mb_wai   []={"ÍáÍâáË"};
const char PY_mb_wan   []={"ÂûÍãÍäÍåÍæÍçÍèÍéÍêÍëÍìÍíÍîÍïÍğÍñÍòÍóØàÜ¹İ¸İÒæıòêçºçşëäîµ÷´"};
const char PY_mb_wang  []={"ÍôÍõÍöÍ÷ÍøÍùÍúÍûÍüÍıØèã¯÷ÍŞÌéş"};
const char PY_mb_wei   []={"ÎªÎ»Î½ÍşÎ¡Î¢Î£Î¤Î¬Î¥Î¦Î§Î¨Î©Î«Î­Î®Î¯Î°Î±Î²Î³Î´ÎµÎ¶Î·Î¸Î¹ÎºÎ¼Î¾Î¿ÎÀÙËÚÃÚóÛ×İÚŞ±àøá¡áËáÍâ¬åÔæ¸ğôì¿çâãÇâ«Úñãíä¢ä¶è¸ê¦ìĞôºöÛàí"};
const char PY_mb_wen   []={"ÎÊÎÄÎÅÎÆÎÁÎÂÎÃÎÇÎÈÎÉØØö©çäãÓãëè·"};
const char PY_mb_weng  []={"ÎËÎÌÎÍİîŞ³"};
const char PY_mb_wo    []={"ÎÒÎÕà¸ÎÏÎĞÎÑÎÓÎÔÎÖÎÎÙÁİ«á¢ö»ä×ë¿íÒ"};
const char PY_mb_wu    []={"ÎåÎïÎğÎñÎçÎèÎéÎäÎê¶ñÎòÎóØ£Î×ÎíÎØÎÙÎÚÎÛÎÜÎİÎŞÎßÎàÎáÎâÎãÎæÎëÎìÎîØõÚùğÄÛØÜÌßíâĞâäâèğÍğíòÚä´å»åÃåüæÄæğÚãè»êõì¶ìÉöÈ÷ù"};
const char PY_mb_xi    []={"Ï£Ï°Ï¦Ï·Ï¸ÎôÎõÎöÎ÷ÎøÎùÎúÎûÎüÎıÎşÏ¡õèÏ¢Ï¤Ï¥Ï§Ï¨ÏªÏ«Ï¬Ï®Ï¯Ï±Ï²Ï´ÏµÏ¶ôËğªåïæÒçôéØŞÉÜçÏ­Ï©Ï³ØÎÙÒÙâÚôÛ­İ¾İßİûßñáãâ¾ãÒä»äÀêØêêì¤ì¨ìäìùìûñ¶ñÓòáó£ó¬ôªô¸ôÑôâõµ÷û"};
const char PY_mb_xia   []={"Ï¹ÏºÏ»Ï¼Ï½Ï¾Ï¿ÏÀÏÁÏÂÏÃÏÄÏÅßÈáòåÚè¦èÔíÌóÁ÷ï"};
const char PY_mb_xian  []={"ÏÖÏÈÏÉÏÓÏÔÏÕÏ×ÏØÏÍÏ³Ï´ÏÆÏÇÏÊÏËÏÌÏÎÏÏÏĞÏÑÏÒÏÙÏÚÏÛÏÜÏİÏŞÏßÙşÜÈİ²Şºá­áıåßæµë¯ìŞììğÂğçğïò¹óÚôÌõ£õĞõÑö±"};
const char PY_mb_xiang []={"ÏñÏòÏó½µÏàÏáÏâÏãÏäÏæÏçÏèÏéÏêÏëÏìÏíÏîÏïÏğÏå÷ÏÜ¼İÙâÃâÔæøç½ó­öß"};
const char PY_mb_xiao  []={"Ğ¡ÏûĞ¤ÏôÏõÏöÏ÷ÏøÏùÏúÏüÏıÏşĞ¢Ğ£Ğ¥Ğ¦Ğ§ßØäìåĞóãóïæçç¯èÉèÕòÙ÷Ì"};
const char PY_mb_xie   []={"Ğ©ĞªĞ«Ğ¬Ğ­Ğ®Ğ¯Ğ°Ğ±Ğ²Ğ³Ğ´ĞµĞ¶Ğ·Ğ¸Ğ¹ĞºĞ»Ğ¼Ñª½âĞ¨Ò¶ÙÉÙôÛÄÛÆŞ¯ß¢â³âİäÍå¬åâç¥çÓé¿éÇò¡õóöÙ÷º"};
const char PY_mb_xin   []={"Ğ½Ğ¾Ğ¿ĞÀĞÁĞÂĞÃĞÄĞÅĞÆÜ°İ·ì§öÎê¿Ø¶âàïâ"};
const char PY_mb_xing  []={"ĞÒÊ¡ĞÇĞÈĞÉĞÊĞËĞÌĞÍĞÎĞÏĞĞĞÑĞÓĞÔĞÕâ¼ÚêÜôÜşß©ã¬íÊ"};
const char PY_mb_xiong []={"ĞÖĞ×ĞØĞÙĞÚĞÛĞÜÜº"};
const char PY_mb_xiu   []={"³ôËŞĞİĞŞĞßĞàĞáĞâĞãĞäĞåßİäåõ÷âÊá¶âÓğ¼÷Û"};
const char PY_mb_xu    []={"ĞøĞ÷ĞæĞçĞèĞéĞêĞëĞìĞíĞîĞïĞğĞñĞòĞóĞôĞõĞöÚ¼ìãÛÃÛ×Ş£äªä°äÓçïèòÓõñãíìôÚõ¯"};
const char PY_mb_xuan  []={"ĞşÑ¡ĞùĞúĞûäÖĞüĞıêÑÑ¤ìÅÑ£Ñ¢ÙØÚÎİæãùäöè¯é¸ìÓŞïíÛîçïàÈ¯"};
const char PY_mb_xue   []={"Ï÷Ñ¥Ñ¦Ñ§Ñ¨Ñ©Ñª÷¨ÚÊàåí´õ½"};
const char PY_mb_xun   []={"Ñ°Ñ®Ñ¸Ñ¶Ñ¯ÑµÑ«Ñ¬Ñ­Ñ±Ñ²Ñ³Ñ´Ñ·Û¨Û÷Ü÷Ş¹á¾áßõ¸öà¿£İ¡Ş¦â´Ùãâşä­ä±êÖñ¿"};
const char PY_mb_ya    []={"ÑÀÑ¿ÑÇÑÆÑ¹ÑÅÑºÑ»Ñ¼Ñ½Ñ¾ÑÂÑÃÑÄÑÈÔşØóÑÁÛëŞëá¬åÂæ«çğèâë²í¼íığéñâ"};
const char PY_mb_yan   []={"ÑÔÑİÑéÑáÑÏÑØÑ×ÑàÑÊÑËÑÙÑÚÑÛÑÌÑÍÑÎÑĞÑÒÑÓÑÕÑÖÑÜÑŞÑßÑâÑãÑäÑÉÑåÑæÑçÑèÑÑãÆåûæÌëÙëçìÍâûÙ²ÙÈÇ¦ÒóØÉØÍØßÙğÚ¥ÚİÚçÛ±Û³Ü¾İÎáÃ÷ÊãÕäÎäÙçüéÜêÌî»óÛõ¦÷Ğ÷ú÷ü"};
const char PY_mb_yang  []={"ÑëÑöÑòÑóÑôÑøÑùÑîÑïí¦ÑêÑìÑíÑğÑõÑñÑ÷Ñúáàâóãóì¾ìÈòÕ÷±"};
const char PY_mb_yao   []={"ÒªÑûÒ§Ò©ÑüÑıÒ¡Ò¢ëÈñºÒ£Ò¤Ò¥Ò¦Ò¨Ò«Ô¿Ø²Ø³çÛßºÑşÄöÅ±½ÄáÅáÊáæçòèÃé÷ê×ï¢ğÎôí÷¥"};
const char PY_mb_ye    []={"Ò²Ò³ÒµÒ¶Ò¹ÒºÒ¬Ò­Ò®Ò¯Ò°Ò±Ò´Ò·Ò¸Ğ°ÑÊÚËÖÑØÌÚşŞŞçğêÊìÇîô"};
const char PY_mb_yi    []={"Ò»ÒÒÒÑÒÔÒäÒåÒéÒêÒëÒìÒæÒ¼Ò½Ò¾Ò¿ÒÀÒÁÒÂÒÃÒÄÒÅÒÆÒÇÒÈÒÉÒÊÒËÒÌÒÍÒÎÒÏÒĞÒÓÒÕÒÖÒ×ÒØÒÙÒÚÒÛÒÜÒİÒŞÒßÒàÒáÒâÒãÒçÒèÒíÒî°¬Î²ÒïØ×ØæØıÙ«Ú±ÚâÛİÛüÜ²ÜÓÜèŞ²ŞÄŞÈŞÚß®ß½ß×ßŞàæá»áÚâ¢âÂâøâùã¨äôåÆæäçËéìéóêİì¥ì½ìÚíôîÆîèï×ïîğêğùñ¯ñ´ñÂòæô¯ôàôèôı÷ğ"};
const char PY_mb_yin   []={"ÒüÒıÓ¡ÒğÒñÒòÒóÒôÒõÒöÒ÷ÒøÒùÒúÒûÒşö¸Ø·ò¾Û´ÛÈÛóÜ§ÜáßÅà³áşâ¹ä¦äÎë³î÷ñ«ñ¿ö¯"};
const char PY_mb_ying  []={"Ó³Ó°Ó¢Ó¨Ó©ÓªÓ«Ó£Ó¤Ó¥Ó¦Ó§Ó¬Ó­Ó®Ó¯Ó±Ó²ÙøİºİÓğĞäëå­äŞçøÛ«ÜãÜşİöŞüàÓâßè¬éºëôñ¨ò£ó¿"};
const char PY_mb_yo    []={"Ó´Óıà¡"};
const char PY_mb_yong  []={"ÓÃÓµÓ¶ÓÂÓ¿Ó·Ó¸Ó¹ÓºÓ»Ó¼Ó½Ó¾ÓÀÓÁÙ¸ÛÕÜ­à¯ã¼çßïŞğ®÷«÷Ó"};
const char PY_mb_you   []={"ÓÈÓĞÓÖÓÕÓ×ÓÑÓÒÓÓÓÄÓÅÓÆÓÇÓÉÓÊÓËÓÌÓÍÓÎÓÏÓÔßÏğàöÏ÷î÷øòÄØüØÕÙ§İ¬İ¯İµŞÌàóå¶èÖéàë»îğòÊòöòøôí"};
const char PY_mb_yu    []={"ÓàÓëÓÚÓèÓîÓñÓêÓıÓşÔ¡ÓãÓØÓÙÓÛÓİÓŞÓßÓáÓâÓäÓåÓæÓçÓéÓìÓíÓïÓğÓòÓóÓôÓõÓöÓ÷ÓøÓùÓúÓÜÓûÓüÔ¢Ô£Ô¤Ô¥Ô¦óÄØ¹ÚÄì¶ÚÍÎµÎ¾Ø®ØñÙ¶İÇİÒİ÷ŞíàôàöáÎáüâÀâÅâ×ãĞå÷åıæ¥æúè¤êÅêìëéì£ìÏìÙìÛí±í²îÚğÁğÖğõğöñ¾ñÁòâòõô§ô¨ö§ö¹"};
const char PY_mb_yuan  []={"Ô­ÔªÔ°Ô±Ô²Ô´ÔµÔ¶Ô¸Ô¹ÔºÔ§Ô¨Ô©Ô«Ô¬Ô®Ô¯Ô³Ô·æÂÜ«Ü¾Şòà÷ãäè¥éÚë¼íóğ°ó¢óîö½"};
const char PY_mb_yue   []={"ÔÂÔÃÔÄÀÖËµÔ»Ô¼Ô½Ô¾Ô¿ÔÀÔÁÙßßÜå®èİéĞë¾îá"};
const char PY_mb_yun   []={"ÔÆÔ±ÔÊÔËÔÎÔÅÔÈÔÉÔÌÔÍìÙÔÏÔĞëµéæÜ¿ÔÇÛ©áñã¢ã³ç¡è¹êÀóŞ"};
const char PY_mb_za    []={"ÔÑÔÒÔÓÔúÕ¦ßÆŞÙ"};
const char PY_mb_zai   []={"ÔÙÔÚÔÔÔÕÔÖÔ×ÔØáÌçŞ"};
const char PY_mb_zan   []={"ÔÛÔÜÔİÔŞêÃô¢ŞÙè¶ôØôõöÉ"};
const char PY_mb_zang  []={"²ØÔßÔàÔáæàê°"};
const char PY_mb_zao   []={"ÔæÔâÔçÔìÔíÔîÔãÔäÔèÔêÔëÔïÔåÔéßğ"};
const char PY_mb_ze    []={"ÔğÔñÔòÔóÕ¦ØÆØÓßõàıåÅê¾óĞóåô·"};
const char PY_mb_zei   []={"Ôô"};
const char PY_mb_zen   []={"ÔõÚÚ"};
const char PY_mb_zeng  []={"ÔöÔ÷ÔøÔùçÕêµîÀï­"};
const char PY_mb_zha   []={"ÔúÕ¢²éÔûÔüÔıÔşÕ¡Õ£Õ¤Õ¥Õ¦Õ§Õ¨Õ©ß¸ßå×õŞêòÆßîà©é«íÄğäö´÷ş"};
const char PY_mb_zhai  []={"Õ¬Õ­Õ®µÔÔñÕªÕ«Õ¯íÎñ©"};
const char PY_mb_zhan  []={"Õ¼Õ½Õ¾Õ¹Õ´ÕÀÕ°Õ±Õ²Õ³ÕµÕ¶Õ·Õ¸Õº²üÕ»Õ¿ÚŞŞøæöì¹"};
const char PY_mb_zhang []={"ÕÅÕÉÕÌÕÍÕÈÕÁÕÂÕÃÕÄÕÆÕÇÕÊÕË³¤ÕÎÕÏá¤áÖâ¯ó¯ØëÛµæÑè°"};
const char PY_mb_zhao  []={"ÕÒÕÙ×¦×ÅÕ×³¯ÕĞÕÑÚ¯ÕÓÕÔÕÕÕÖÕØîÈóÉßúèş"};
const char PY_mb_zhe   []={"ÕÚÕÛÕÜÕİÕŞÕßÕàÕáÕâÕã×ÅÚØß¡èÏéüíİğÑñŞòØô÷"};
const char PY_mb_zhen  []={"ÕæÕêÕëÕğÕñÕïÕóÕòÕìÕíÕäÕîÕåÕçóğÕéÖ¡ÛÚÕèİèä¥äÚçÇèåé©é»éôêâëÓëŞìõî³ğ¡ğ²"};
const char PY_mb_zheng []={"ÕıÖ¤ÕôÕõÕöÕ÷ÕøÕùÕúÕûÕüÕşÖ¢Ö£Úºá¿áçîÛï£óİöë"};
const char PY_mb_zhi   []={"Ö»Ö°Ê¶Ö´ÖµÖ±Ö²Ö³ÖÎÖ§Ö½Ö¾Ö·Ö¸ÖÊÖÃÖÆÖ¹ÖÁÖ¶Ö¥Ö®Ö­Ö¼Ö¦ÖªÖ«Ö¬Ö¯ÖºÖ¿ÖÀÖÂÖÄÖÅÖÇÖÈÖÉÖ¨Ö©ÖËÖÌÖÍÖÏè×ÜÆØ´ÚìÛ¤ÛúŞıàùáçâºâååéåëæïèÎèÙèäéòéùêŞëÕëùìíìóíéïôğºğëòÎôêõ¥õÅõÙõÜõôö£"};
const char PY_mb_zhong []={"ÖĞÖÚÖÒÖÓÖÔÖÕÖÖÖ×ÖØÖÙÖÑÚ£âìïñó®ô±õà"};
const char PY_mb_zhou  []={"ÖÛÖÜÖİÖŞÖßÖàÖáÖâÖãÖäÖåÖæÖçÖèİ§ßúæ¨æûç§ëĞíØô¦ôíôü"};
const char PY_mb_zhu   []={"Ö÷×¡×¢×£ÖñÖéÖêÖëÖìÖíÖîÖïÖğÖòÖóÖôÖõÖöÖøÖùÖúÖûÖüÖıÖş×¤ØùóÃóçÙªÊôÊõÛ¥ÜÑÜïä¨ä¾äóèÌéÆéÍìÄîùğæğññÒô¶ôãõî÷æØ¼"};
const char PY_mb_zhua  []={"×¥×¦ÎÎ"};
const char PY_mb_zhuai []={"×§×ª"};
const char PY_mb_zhuan []={"´«×¨×©×ª×«×¬×­ßùâÍãçò§"};
const char PY_mb_zhuang[]={"´±×®×¯×°×±×²×³×´ŞÊí°"};
const char PY_mb_zhui  []={"×µ×¶×·×¸×¹×ºã·æíçÄö¿"};
const char PY_mb_zhun  []={"×»×¼â½ëÆñ¸"};
const char PY_mb_zhuo  []={"×Å×½×¾×¿×À×Æ×Â×Ç×Ã×Á×ÄÙ¾ÚÂßªä·äÃåªìÌìúí½ïí"};
const char PY_mb_zi    []={"×Ô×Ó×Ö×Ğ×È×É×Ê×Ë×Ì×Í×Î×Ï×Ñ×Ò×Õö·æ¢Ö¨áÑÚÑÜëæÜç»è÷ê¢êßí§íöïÅïöñèóÊôÒôôõşö¤öö÷Ú"};
const char PY_mb_zong  []={"×Ú×Û×Ü×××Ø×Ù×İôÕÙÌèÈëê"};
const char PY_mb_zou   []={"×ß×à×á×ŞÚÁÚîÛ¸æãöí"};
const char PY_mb_zu    []={"×ã×é×ä×å×â×æ×ç×èÙŞİÏïß"};
const char PY_mb_zuan  []={"×êß¬×ëçÚõò"};
const char PY_mb_zui   []={"×î×ï×ì×íŞ©õş"};
const char PY_mb_zun   []={"×ğ×ñé×÷®ß¤"};
const char PY_mb_zuo   []={"×ó×ô×ö×÷×ø×ù×ò´éßò×õÚè×ÁàÜâôëÑìñíÄõ¡"};

/* Æ´ÒôË÷Òı±í */
const py_index py_index3[]=
{
{(unsigned char*)"" ,(unsigned char*)"",(unsigned char*)PY_mb_space},
{(unsigned char*)"2",(unsigned char*)"a",(unsigned char*)PY_mb_a},
{(unsigned char*)"3",(unsigned char*)"e",(unsigned char*)PY_mb_e},
{(unsigned char*)"6",(unsigned char*)"o",(unsigned char*)PY_mb_o},
{(unsigned char*)"24",(unsigned char*)"ai",(unsigned char*)PY_mb_ai},
{(unsigned char*)"26",(unsigned char*)"an",(unsigned char*)PY_mb_an},
{(unsigned char*)"26",(unsigned char*)"ao",(unsigned char*)PY_mb_ao},
{(unsigned char*)"22",(unsigned char*)"ba",(unsigned char*)PY_mb_ba},
{(unsigned char*)"24",(unsigned char*)"bi",(unsigned char*)PY_mb_bi},
{(unsigned char*)"26",(unsigned char*)"bo",(unsigned char*)PY_mb_bo},
{(unsigned char*)"28",(unsigned char*)"bu",(unsigned char*)PY_mb_bu},
{(unsigned char*)"22",(unsigned char*)"ca",(unsigned char*)PY_mb_ca},
{(unsigned char*)"23",(unsigned char*)"ce",(unsigned char*)PY_mb_ce},
{(unsigned char*)"24",(unsigned char*)"ci",(unsigned char*)PY_mb_ci},
{(unsigned char*)"28",(unsigned char*)"cu",(unsigned char*)PY_mb_cu},
{(unsigned char*)"32",(unsigned char*)"da",(unsigned char*)PY_mb_da},
{(unsigned char*)"33",(unsigned char*)"de",(unsigned char*)PY_mb_de},
{(unsigned char*)"34",(unsigned char*)"di",(unsigned char*)PY_mb_di},
{(unsigned char*)"38",(unsigned char*)"du",(unsigned char*)PY_mb_du},
{(unsigned char*)"36",(unsigned char*)"en",(unsigned char*)PY_mb_en},
{(unsigned char*)"37",(unsigned char*)"er",(unsigned char*)PY_mb_er},
{(unsigned char*)"32",(unsigned char*)"fa",(unsigned char*)PY_mb_fa},
{(unsigned char*)"36",(unsigned char*)"fo",(unsigned char*)PY_mb_fo},
{(unsigned char*)"38",(unsigned char*)"fu",(unsigned char*)PY_mb_fu},
{(unsigned char*)"42",(unsigned char*)"ha",(unsigned char*)PY_mb_ha},
{(unsigned char*)"42",(unsigned char*)"ga",(unsigned char*)PY_mb_ga},
{(unsigned char*)"43",(unsigned char*)"ge",(unsigned char*)PY_mb_ge},
{(unsigned char*)"43",(unsigned char*)"he",(unsigned char*)PY_mb_he},
{(unsigned char*)"48",(unsigned char*)"gu",(unsigned char*)PY_mb_gu},
{(unsigned char*)"48",(unsigned char*)"hu",(unsigned char*)PY_mb_hu},
{(unsigned char*)"54",(unsigned char*)"ji",(unsigned char*)PY_mb_ji},
{(unsigned char*)"58",(unsigned char*)"ju",(unsigned char*)PY_mb_ju},
{(unsigned char*)"52",(unsigned char*)"ka",(unsigned char*)PY_mb_ka},
{(unsigned char*)"53",(unsigned char*)"ke",(unsigned char*)PY_mb_ke},
{(unsigned char*)"58",(unsigned char*)"ku",(unsigned char*)PY_mb_ku},
{(unsigned char*)"52",(unsigned char*)"la",(unsigned char*)PY_mb_la},
{(unsigned char*)"53",(unsigned char*)"le",(unsigned char*)PY_mb_le},
{(unsigned char*)"54",(unsigned char*)"li",(unsigned char*)PY_mb_li},
{(unsigned char*)"58",(unsigned char*)"lu",(unsigned char*)PY_mb_lu},
{(unsigned char*)"58",(unsigned char*)"lv",(unsigned char*)PY_mb_lv},
{(unsigned char*)"62",(unsigned char*)"ma",(unsigned char*)PY_mb_ma},
{(unsigned char*)"63",(unsigned char*)"me",(unsigned char*)PY_mb_me},
{(unsigned char*)"64",(unsigned char*)"mi",(unsigned char*)PY_mb_mi},
{(unsigned char*)"66",(unsigned char*)"mo",(unsigned char*)PY_mb_mo},
{(unsigned char*)"68",(unsigned char*)"mu",(unsigned char*)PY_mb_mu},
{(unsigned char*)"62",(unsigned char*)"na",(unsigned char*)PY_mb_na},
{(unsigned char*)"63",(unsigned char*)"ne",(unsigned char*)PY_mb_ne},
{(unsigned char*)"64",(unsigned char*)"ni",(unsigned char*)PY_mb_ni},
{(unsigned char*)"68",(unsigned char*)"nu",(unsigned char*)PY_mb_nu},
{(unsigned char*)"68",(unsigned char*)"nv",(unsigned char*)PY_mb_nv},
{(unsigned char*)"68",(unsigned char*)"ou",(unsigned char*)PY_mb_ou},
{(unsigned char*)"72",(unsigned char*)"pa",(unsigned char*)PY_mb_pa},
{(unsigned char*)"74",(unsigned char*)"pi",(unsigned char*)PY_mb_pi},
{(unsigned char*)"76",(unsigned char*)"po",(unsigned char*)PY_mb_po},
{(unsigned char*)"78",(unsigned char*)"pu",(unsigned char*)PY_mb_pu},
{(unsigned char*)"74",(unsigned char*)"qi",(unsigned char*)PY_mb_qi},
{(unsigned char*)"78",(unsigned char*)"qu",(unsigned char*)PY_mb_qu},
{(unsigned char*)"73",(unsigned char*)"re",(unsigned char*)PY_mb_re},
{(unsigned char*)"74",(unsigned char*)"ri",(unsigned char*)PY_mb_ri},
{(unsigned char*)"78",(unsigned char*)"ru",(unsigned char*)PY_mb_ru},
{(unsigned char*)"72",(unsigned char*)"sa",(unsigned char*)PY_mb_sa},
{(unsigned char*)"73",(unsigned char*)"se",(unsigned char*)PY_mb_se},
{(unsigned char*)"74",(unsigned char*)"si",(unsigned char*)PY_mb_si},
{(unsigned char*)"78",(unsigned char*)"su",(unsigned char*)PY_mb_su},
{(unsigned char*)"82",(unsigned char*)"ta",(unsigned char*)PY_mb_ta},
{(unsigned char*)"83",(unsigned char*)"te",(unsigned char*)PY_mb_te},
{(unsigned char*)"84",(unsigned char*)"ti",(unsigned char*)PY_mb_ti},
{(unsigned char*)"88",(unsigned char*)"tu",(unsigned char*)PY_mb_tu},
{(unsigned char*)"92",(unsigned char*)"wa",(unsigned char*)PY_mb_wa},
{(unsigned char*)"96",(unsigned char*)"wo",(unsigned char*)PY_mb_wo},
{(unsigned char*)"98",(unsigned char*)"wu",(unsigned char*)PY_mb_wu},
{(unsigned char*)"94",(unsigned char*)"xi",(unsigned char*)PY_mb_xi},
{(unsigned char*)"98",(unsigned char*)"xu",(unsigned char*)PY_mb_xu},
{(unsigned char*)"92",(unsigned char*)"ya",(unsigned char*)PY_mb_ya},
{(unsigned char*)"93",(unsigned char*)"ye",(unsigned char*)PY_mb_ye},
{(unsigned char*)"94",(unsigned char*)"yi",(unsigned char*)PY_mb_yi},
{(unsigned char*)"96",(unsigned char*)"yo",(unsigned char*)PY_mb_yo},
{(unsigned char*)"98",(unsigned char*)"yu",(unsigned char*)PY_mb_yu},
{(unsigned char*)"92",(unsigned char*)"za",(unsigned char*)PY_mb_za},
{(unsigned char*)"93",(unsigned char*)"ze",(unsigned char*)PY_mb_ze},
{(unsigned char*)"94",(unsigned char*)"zi",(unsigned char*)PY_mb_zi},
{(unsigned char*)"98",(unsigned char*)"zu",(unsigned char*)PY_mb_zu},
{(unsigned char*)"264",(unsigned char*)"ang",(unsigned char*)PY_mb_ang},
{(unsigned char*)"224",(unsigned char*)"bai",(unsigned char*)PY_mb_bai},
{(unsigned char*)"226",(unsigned char*)"ban",(unsigned char*)PY_mb_ban},
{(unsigned char*)"226",(unsigned char*)"bao",(unsigned char*)PY_mb_bao},
{(unsigned char*)"234",(unsigned char*)"bei",(unsigned char*)PY_mb_bei},
{(unsigned char*)"236",(unsigned char*)"ben",(unsigned char*)PY_mb_ben},
{(unsigned char*)"243",(unsigned char*)"bie",(unsigned char*)PY_mb_bie},
{(unsigned char*)"246",(unsigned char*)"bin",(unsigned char*)PY_mb_bin},
{(unsigned char*)"224",(unsigned char*)"cai",(unsigned char*)PY_mb_cai},
{(unsigned char*)"226",(unsigned char*)"can",(unsigned char*)PY_mb_can},
{(unsigned char*)"226",(unsigned char*)"cao",(unsigned char*)PY_mb_cao},
{(unsigned char*)"242",(unsigned char*)"cha",(unsigned char*)PY_mb_cha},
{(unsigned char*)"243",(unsigned char*)"che",(unsigned char*)PY_mb_che},
{(unsigned char*)"244",(unsigned char*)"chi",(unsigned char*)PY_mb_chi},
{(unsigned char*)"248",(unsigned char*)"chu",(unsigned char*)PY_mb_chu},
{(unsigned char*)"268",(unsigned char*)"cou",(unsigned char*)PY_mb_cou},
{(unsigned char*)"284",(unsigned char*)"cui",(unsigned char*)PY_mb_cui},
{(unsigned char*)"286",(unsigned char*)"cun",(unsigned char*)PY_mb_cun},
{(unsigned char*)"286",(unsigned char*)"cuo",(unsigned char*)PY_mb_cuo},
{(unsigned char*)"324",(unsigned char*)"dai",(unsigned char*)PY_mb_dai},
{(unsigned char*)"326",(unsigned char*)"dan",(unsigned char*)PY_mb_dan},
{(unsigned char*)"326",(unsigned char*)"dao",(unsigned char*)PY_mb_dao},
{(unsigned char*)"334",(unsigned char*)"dei",(unsigned char*)PY_mb_dei},
{(unsigned char*)"343",(unsigned char*)"die",(unsigned char*)PY_mb_die},
{(unsigned char*)"348",(unsigned char*)"diu",(unsigned char*)PY_mb_diu},
{(unsigned char*)"368",(unsigned char*)"dou",(unsigned char*)PY_mb_dou},
{(unsigned char*)"384",(unsigned char*)"dui",(unsigned char*)PY_mb_dui},
{(unsigned char*)"386",(unsigned char*)"dun",(unsigned char*)PY_mb_dun},
{(unsigned char*)"386",(unsigned char*)"duo",(unsigned char*)PY_mb_duo},
{(unsigned char*)"326",(unsigned char*)"fan",(unsigned char*)PY_mb_fan},
{(unsigned char*)"334",(unsigned char*)"fei",(unsigned char*)PY_mb_fei},
{(unsigned char*)"336",(unsigned char*)"fen",(unsigned char*)PY_mb_fen},
{(unsigned char*)"368",(unsigned char*)"fou",(unsigned char*)PY_mb_fou},
{(unsigned char*)"424",(unsigned char*)"gai",(unsigned char*)PY_mb_gai},
{(unsigned char*)"426",(unsigned char*)"gan",(unsigned char*)PY_mb_gan},
{(unsigned char*)"426",(unsigned char*)"gao",(unsigned char*)PY_mb_gao},
{(unsigned char*)"434",(unsigned char*)"gei",(unsigned char*)PY_mb_gei},
{(unsigned char*)"436",(unsigned char*)"gen",(unsigned char*)PY_mb_gan},
{(unsigned char*)"468",(unsigned char*)"gou",(unsigned char*)PY_mb_gou},
{(unsigned char*)"482",(unsigned char*)"gua",(unsigned char*)PY_mb_gua},
{(unsigned char*)"484",(unsigned char*)"gui",(unsigned char*)PY_mb_gui},
{(unsigned char*)"486",(unsigned char*)"gun",(unsigned char*)PY_mb_gun},
{(unsigned char*)"486",(unsigned char*)"guo",(unsigned char*)PY_mb_guo},
{(unsigned char*)"424",(unsigned char*)"hai",(unsigned char*)PY_mb_hai},
{(unsigned char*)"426",(unsigned char*)"han",(unsigned char*)PY_mb_han},
{(unsigned char*)"426",(unsigned char*)"hao",(unsigned char*)PY_mb_hao},
{(unsigned char*)"434",(unsigned char*)"hei",(unsigned char*)PY_mb_hei},
{(unsigned char*)"436",(unsigned char*)"hen",(unsigned char*)PY_mb_hen},
{(unsigned char*)"468",(unsigned char*)"hou",(unsigned char*)PY_mb_hou},
{(unsigned char*)"482",(unsigned char*)"hua",(unsigned char*)PY_mb_hua},
{(unsigned char*)"484",(unsigned char*)"hui",(unsigned char*)PY_mb_hui},
{(unsigned char*)"486",(unsigned char*)"hun",(unsigned char*)PY_mb_hun},
{(unsigned char*)"486",(unsigned char*)"huo",(unsigned char*)PY_mb_huo},
{(unsigned char*)"542",(unsigned char*)"jia",(unsigned char*)PY_mb_jia},
{(unsigned char*)"543",(unsigned char*)"jie",(unsigned char*)PY_mb_jie},
{(unsigned char*)"546",(unsigned char*)"jin",(unsigned char*)PY_mb_jin},
{(unsigned char*)"548",(unsigned char*)"jiu",(unsigned char*)PY_mb_jiu},
{(unsigned char*)"583",(unsigned char*)"jue",(unsigned char*)PY_mb_jue},
{(unsigned char*)"586",(unsigned char*)"jun",(unsigned char*)PY_mb_jun},
{(unsigned char*)"524",(unsigned char*)"kai",(unsigned char*)PY_mb_kai},
{(unsigned char*)"526",(unsigned char*)"kan",(unsigned char*)PY_mb_kan},
{(unsigned char*)"526",(unsigned char*)"kao",(unsigned char*)PY_mb_kao},
{(unsigned char*)"536",(unsigned char*)"ken",(unsigned char*)PY_mb_ken},
{(unsigned char*)"568",(unsigned char*)"kou",(unsigned char*)PY_mb_kou},
{(unsigned char*)"582",(unsigned char*)"kua",(unsigned char*)PY_mb_kua},
{(unsigned char*)"584",(unsigned char*)"kui",(unsigned char*)PY_mb_kui},
{(unsigned char*)"586",(unsigned char*)"kun",(unsigned char*)PY_mb_kun},
{(unsigned char*)"586",(unsigned char*)"kuo",(unsigned char*)PY_mb_kuo},
{(unsigned char*)"524",(unsigned char*)"lai",(unsigned char*)PY_mb_lai},
{(unsigned char*)"526",(unsigned char*)"lan",(unsigned char*)PY_mb_lan},
{(unsigned char*)"526",(unsigned char*)"lao",(unsigned char*)PY_mb_lao},
{(unsigned char*)"534",(unsigned char*)"lei",(unsigned char*)PY_mb_lei},
{(unsigned char*)"543",(unsigned char*)"lie",(unsigned char*)PY_mb_lie},
{(unsigned char*)"546",(unsigned char*)"lin",(unsigned char*)PY_mb_lin},
{(unsigned char*)"548",(unsigned char*)"liu",(unsigned char*)PY_mb_liu},
{(unsigned char*)"568",(unsigned char*)"lou",(unsigned char*)PY_mb_lou},
{(unsigned char*)"583",(unsigned char*)"lue",(unsigned char*)PY_mb_lue},
{(unsigned char*)"586",(unsigned char*)"lun",(unsigned char*)PY_mb_lun},
{(unsigned char*)"586",(unsigned char*)"luo",(unsigned char*)PY_mb_luo},
{(unsigned char*)"624",(unsigned char*)"mai",(unsigned char*)PY_mb_mai},
{(unsigned char*)"626",(unsigned char*)"man",(unsigned char*)PY_mb_man},
{(unsigned char*)"626",(unsigned char*)"mao",(unsigned char*)PY_mb_mao},
{(unsigned char*)"634",(unsigned char*)"mei",(unsigned char*)PY_mb_mei},
{(unsigned char*)"636",(unsigned char*)"men",(unsigned char*)PY_mb_men},
{(unsigned char*)"643",(unsigned char*)"mie",(unsigned char*)PY_mb_mie},
{(unsigned char*)"646",(unsigned char*)"min",(unsigned char*)PY_mb_min},
{(unsigned char*)"648",(unsigned char*)"miu",(unsigned char*)PY_mb_miu},
{(unsigned char*)"668",(unsigned char*)"mou",(unsigned char*)PY_mb_mou},
{(unsigned char*)"624",(unsigned char*)"nai",(unsigned char*)PY_mb_nai},
{(unsigned char*)"626",(unsigned char*)"nan",(unsigned char*)PY_mb_nan},
{(unsigned char*)"626",(unsigned char*)"nao",(unsigned char*)PY_mb_nao},
{(unsigned char*)"634",(unsigned char*)"nei",(unsigned char*)PY_mb_nei},
{(unsigned char*)"636",(unsigned char*)"nen",(unsigned char*)PY_mb_nen},
{(unsigned char*)"643",(unsigned char*)"nie",(unsigned char*)PY_mb_nie},
{(unsigned char*)"646",(unsigned char*)"nin",(unsigned char*)PY_mb_nin},
{(unsigned char*)"648",(unsigned char*)"niu",(unsigned char*)PY_mb_niu},
{(unsigned char*)"683",(unsigned char*)"nue",(unsigned char*)PY_mb_nue},
{(unsigned char*)"686",(unsigned char*)"nuo",(unsigned char*)PY_mb_nuo},
{(unsigned char*)"724",(unsigned char*)"pai",(unsigned char*)PY_mb_pai},
{(unsigned char*)"726",(unsigned char*)"pan",(unsigned char*)PY_mb_pan},
{(unsigned char*)"726",(unsigned char*)"pao",(unsigned char*)PY_mb_pao},
{(unsigned char*)"734",(unsigned char*)"pei",(unsigned char*)PY_mb_pei},
{(unsigned char*)"736",(unsigned char*)"pen",(unsigned char*)PY_mb_pen},
{(unsigned char*)"743",(unsigned char*)"pie",(unsigned char*)PY_mb_pie},
{(unsigned char*)"746",(unsigned char*)"pin",(unsigned char*)PY_mb_pin},
{(unsigned char*)"768",(unsigned char*)"pou",(unsigned char*)PY_mb_pou},
{(unsigned char*)"742",(unsigned char*)"qia",(unsigned char*)PY_mb_qia},
{(unsigned char*)"743",(unsigned char*)"qie",(unsigned char*)PY_mb_qie},
{(unsigned char*)"746",(unsigned char*)"qin",(unsigned char*)PY_mb_qin},
{(unsigned char*)"748",(unsigned char*)"qiu",(unsigned char*)PY_mb_qiu},
{(unsigned char*)"783",(unsigned char*)"que",(unsigned char*)PY_mb_que},
{(unsigned char*)"786",(unsigned char*)"qun",(unsigned char*)PY_mb_qun},
{(unsigned char*)"726",(unsigned char*)"ran",(unsigned char*)PY_mb_ran},
{(unsigned char*)"726",(unsigned char*)"rao",(unsigned char*)PY_mb_rao},
{(unsigned char*)"736",(unsigned char*)"ren",(unsigned char*)PY_mb_ren},
{(unsigned char*)"768",(unsigned char*)"rou",(unsigned char*)PY_mb_rou},
{(unsigned char*)"784",(unsigned char*)"rui",(unsigned char*)PY_mb_rui},
{(unsigned char*)"786",(unsigned char*)"run",(unsigned char*)PY_mb_run},
{(unsigned char*)"786",(unsigned char*)"ruo",(unsigned char*)PY_mb_ruo},
{(unsigned char*)"724",(unsigned char*)"sai",(unsigned char*)PY_mb_sai},
{(unsigned char*)"726",(unsigned char*)"sao",(unsigned char*)PY_mb_sao},
{(unsigned char*)"726",(unsigned char*)"san",(unsigned char*)PY_mb_san},
{(unsigned char*)"736",(unsigned char*)"sen",(unsigned char*)PY_mb_sen},
{(unsigned char*)"742",(unsigned char*)"sha",(unsigned char*)PY_mb_sha},
{(unsigned char*)"743",(unsigned char*)"she",(unsigned char*)PY_mb_she},
{(unsigned char*)"744",(unsigned char*)"shi",(unsigned char*)PY_mb_shi},
{(unsigned char*)"748",(unsigned char*)"shu",(unsigned char*)PY_mb_shu},
{(unsigned char*)"768",(unsigned char*)"sou",(unsigned char*)PY_mb_sou},
{(unsigned char*)"784",(unsigned char*)"sui",(unsigned char*)PY_mb_sui},
{(unsigned char*)"786",(unsigned char*)"sun",(unsigned char*)PY_mb_sun},
{(unsigned char*)"786",(unsigned char*)"suo",(unsigned char*)PY_mb_suo},
{(unsigned char*)"824",(unsigned char*)"tai",(unsigned char*)PY_mb_tai},
{(unsigned char*)"826",(unsigned char*)"tan",(unsigned char*)PY_mb_tan},
{(unsigned char*)"826",(unsigned char*)"tao",(unsigned char*)PY_mb_tao},
{(unsigned char*)"843",(unsigned char*)"tie",(unsigned char*)PY_mb_tie},
{(unsigned char*)"868",(unsigned char*)"tou",(unsigned char*)PY_mb_tou},
{(unsigned char*)"884",(unsigned char*)"tui",(unsigned char*)PY_mb_tui},
{(unsigned char*)"886",(unsigned char*)"tun",(unsigned char*)PY_mb_tun},
{(unsigned char*)"886",(unsigned char*)"tuo",(unsigned char*)PY_mb_tuo},
{(unsigned char*)"924",(unsigned char*)"wai",(unsigned char*)PY_mb_wai},
{(unsigned char*)"926",(unsigned char*)"wan",(unsigned char*)PY_mb_wan},
{(unsigned char*)"934",(unsigned char*)"wei",(unsigned char*)PY_mb_wei},
{(unsigned char*)"936",(unsigned char*)"wen",(unsigned char*)PY_mb_wen},
{(unsigned char*)"942",(unsigned char*)"xia",(unsigned char*)PY_mb_xia},
{(unsigned char*)"943",(unsigned char*)"xie",(unsigned char*)PY_mb_xie},
{(unsigned char*)"946",(unsigned char*)"xin",(unsigned char*)PY_mb_xin},
{(unsigned char*)"948",(unsigned char*)"xiu",(unsigned char*)PY_mb_xiu},
{(unsigned char*)"983",(unsigned char*)"xue",(unsigned char*)PY_mb_xue},
{(unsigned char*)"986",(unsigned char*)"xun",(unsigned char*)PY_mb_xun},
{(unsigned char*)"926",(unsigned char*)"yan",(unsigned char*)PY_mb_yan},
{(unsigned char*)"926",(unsigned char*)"yao",(unsigned char*)PY_mb_yao},
{(unsigned char*)"946",(unsigned char*)"yin",(unsigned char*)PY_mb_yin},
{(unsigned char*)"968",(unsigned char*)"you",(unsigned char*)PY_mb_you},
{(unsigned char*)"983",(unsigned char*)"yue",(unsigned char*)PY_mb_yue},
{(unsigned char*)"986",(unsigned char*)"yun",(unsigned char*)PY_mb_yun},
{(unsigned char*)"924",(unsigned char*)"zai",(unsigned char*)PY_mb_zai},
{(unsigned char*)"926",(unsigned char*)"zan",(unsigned char*)PY_mb_zan},
{(unsigned char*)"926",(unsigned char*)"zao",(unsigned char*)PY_mb_zao},
{(unsigned char*)"934",(unsigned char*)"zei",(unsigned char*)PY_mb_zei},
{(unsigned char*)"936",(unsigned char*)"zen",(unsigned char*)PY_mb_zen},
{(unsigned char*)"942",(unsigned char*)"zha",(unsigned char*)PY_mb_zha},
{(unsigned char*)"943",(unsigned char*)"zhe",(unsigned char*)PY_mb_zhe},
{(unsigned char*)"944",(unsigned char*)"zhi",(unsigned char*)PY_mb_zhi},
{(unsigned char*)"948",(unsigned char*)"zhu",(unsigned char*)PY_mb_zhu},
{(unsigned char*)"968",(unsigned char*)"zou",(unsigned char*)PY_mb_zou},
{(unsigned char*)"984",(unsigned char*)"zui",(unsigned char*)PY_mb_zui},
{(unsigned char*)"986",(unsigned char*)"zun",(unsigned char*)PY_mb_zun},
{(unsigned char*)"986",(unsigned char*)"zuo",(unsigned char*)PY_mb_zuo},
{(unsigned char*)"2264",(unsigned char*)"bang",(unsigned char*)PY_mb_bang},
{(unsigned char*)"2364",(unsigned char*)"beng",(unsigned char*)PY_mb_beng},
{(unsigned char*)"2426",(unsigned char*)"bian",(unsigned char*)PY_mb_bian},
{(unsigned char*)"2426",(unsigned char*)"biao",(unsigned char*)PY_mb_biao},
{(unsigned char*)"2464",(unsigned char*)"bing",(unsigned char*)PY_mb_bing},
{(unsigned char*)"2264",(unsigned char*)"cang",(unsigned char*)PY_mb_cang},
{(unsigned char*)"2364",(unsigned char*)"ceng",(unsigned char*)PY_mb_ceng},
{(unsigned char*)"2424",(unsigned char*)"chai",(unsigned char*)PY_mb_chai},
{(unsigned char*)"2426",(unsigned char*)"chan",(unsigned char*)PY_mb_chan},
{(unsigned char*)"2426",(unsigned char*)"chao",(unsigned char*)PY_mb_chao},
{(unsigned char*)"2436",(unsigned char*)"chen",(unsigned char*)PY_mb_chen},
{(unsigned char*)"2468",(unsigned char*)"chou",(unsigned char*)PY_mb_chou},
{(unsigned char*)"2484",(unsigned char*)"chuai",(unsigned char*)PY_mb_chuai},
{(unsigned char*)"2484",(unsigned char*)"chui",(unsigned char*)PY_mb_chui},
{(unsigned char*)"2486",(unsigned char*)"chun",(unsigned char*)PY_mb_chun},
{(unsigned char*)"2486",(unsigned char*)"chuo",(unsigned char*)PY_mb_chuo},
{(unsigned char*)"2664",(unsigned char*)"cong",(unsigned char*)PY_mb_cong},
{(unsigned char*)"2826",(unsigned char*)"cuan",(unsigned char*)PY_mb_cuan},
{(unsigned char*)"3264",(unsigned char*)"dang",(unsigned char*)PY_mb_dang},
{(unsigned char*)"3364",(unsigned char*)"deng",(unsigned char*)PY_mb_deng},
{(unsigned char*)"3426",(unsigned char*)"dian",(unsigned char*)PY_mb_dian},
{(unsigned char*)"3426",(unsigned char*)"diao",(unsigned char*)PY_mb_diao},
{(unsigned char*)"3464",(unsigned char*)"ding",(unsigned char*)PY_mb_ding},
{(unsigned char*)"3664",(unsigned char*)"dong",(unsigned char*)PY_mb_dong},
{(unsigned char*)"3826",(unsigned char*)"duan",(unsigned char*)PY_mb_duan},
{(unsigned char*)"3264",(unsigned char*)"fang",(unsigned char*)PY_mb_fang},
{(unsigned char*)"3364",(unsigned char*)"feng",(unsigned char*)PY_mb_feng},
{(unsigned char*)"4264",(unsigned char*)"gang",(unsigned char*)PY_mb_gang},
{(unsigned char*)"4364",(unsigned char*)"geng",(unsigned char*)PY_mb_geng},
{(unsigned char*)"4664",(unsigned char*)"gong",(unsigned char*)PY_mb_gong},
{(unsigned char*)"4824",(unsigned char*)"guai",(unsigned char*)PY_mb_guai},
{(unsigned char*)"4826",(unsigned char*)"guan",(unsigned char*)PY_mb_guan},
{(unsigned char*)"4264",(unsigned char*)"hang",(unsigned char*)PY_mb_hang},
{(unsigned char*)"4364",(unsigned char*)"heng",(unsigned char*)PY_mb_heng},
{(unsigned char*)"4664",(unsigned char*)"hong",(unsigned char*)PY_mb_hong},
{(unsigned char*)"4823",(unsigned char*)"huai",(unsigned char*)PY_mb_huai},
{(unsigned char*)"4826",(unsigned char*)"huan",(unsigned char*)PY_mb_huan},
{(unsigned char*)"5426",(unsigned char*)"jian",(unsigned char*)PY_mb_jian},
{(unsigned char*)"5426",(unsigned char*)"jiao",(unsigned char*)PY_mb_jiao},
{(unsigned char*)"5464",(unsigned char*)"jing",(unsigned char*)PY_mb_jing},
{(unsigned char*)"5826",(unsigned char*)"juan",(unsigned char*)PY_mb_juan},
{(unsigned char*)"5264",(unsigned char*)"kang",(unsigned char*)PY_mb_kang},
{(unsigned char*)"5364",(unsigned char*)"keng",(unsigned char*)PY_mb_keng},
{(unsigned char*)"5664",(unsigned char*)"kong",(unsigned char*)PY_mb_kong},
{(unsigned char*)"5824",(unsigned char*)"kuai",(unsigned char*)PY_mb_kuai},
{(unsigned char*)"5826",(unsigned char*)"kuan",(unsigned char*)PY_mb_kuan},
{(unsigned char*)"5264",(unsigned char*)"lang",(unsigned char*)PY_mb_lang},
{(unsigned char*)"5366",(unsigned char*)"leng",(unsigned char*)PY_mb_leng},
{(unsigned char*)"5426",(unsigned char*)"lian",(unsigned char*)PY_mb_lian},
{(unsigned char*)"5426",(unsigned char*)"liao",(unsigned char*)PY_mb_liao},
{(unsigned char*)"5464",(unsigned char*)"ling",(unsigned char*)PY_mb_ling},
{(unsigned char*)"5664",(unsigned char*)"long",(unsigned char*)PY_mb_long},
{(unsigned char*)"5826",(unsigned char*)"luan",(unsigned char*)PY_mb_luan},
{(unsigned char*)"6264",(unsigned char*)"mang",(unsigned char*)PY_mb_mang},
{(unsigned char*)"6364",(unsigned char*)"meng",(unsigned char*)PY_mb_meng},
{(unsigned char*)"6426",(unsigned char*)"mian",(unsigned char*)PY_mb_mian},
{(unsigned char*)"6426",(unsigned char*)"miao",(unsigned char*)PY_mb_miao},
{(unsigned char*)"6464",(unsigned char*)"ming",(unsigned char*)PY_mb_ming},
{(unsigned char*)"6264",(unsigned char*)"nang",(unsigned char*)PY_mb_nang},
{(unsigned char*)"6364",(unsigned char*)"neng",(unsigned char*)PY_mb_neng},
{(unsigned char*)"6426",(unsigned char*)"nian",(unsigned char*)PY_mb_nian},
{(unsigned char*)"6426",(unsigned char*)"niao",(unsigned char*)PY_mb_niao},
{(unsigned char*)"6464",(unsigned char*)"ning",(unsigned char*)PY_mb_ning},
{(unsigned char*)"6664",(unsigned char*)"nong",(unsigned char*)PY_mb_nong},
{(unsigned char*)"6826",(unsigned char*)"nuan",(unsigned char*)PY_mb_nuan},
{(unsigned char*)"7264",(unsigned char*)"pang",(unsigned char*)PY_mb_pang},
{(unsigned char*)"7364",(unsigned char*)"peng",(unsigned char*)PY_mb_peng},
{(unsigned char*)"7426",(unsigned char*)"pian",(unsigned char*)PY_mb_pian},
{(unsigned char*)"7426",(unsigned char*)"piao",(unsigned char*)PY_mb_piao},
{(unsigned char*)"7464",(unsigned char*)"ping",(unsigned char*)PY_mb_ping},
{(unsigned char*)"7426",(unsigned char*)"qian",(unsigned char*)PY_mb_qian},
{(unsigned char*)"7426",(unsigned char*)"qiao",(unsigned char*)PY_mb_qiao},
{(unsigned char*)"7464",(unsigned char*)"qing",(unsigned char*)PY_mb_qing},
{(unsigned char*)"7826",(unsigned char*)"quan",(unsigned char*)PY_mb_quan},
{(unsigned char*)"7264",(unsigned char*)"rang",(unsigned char*)PY_mb_rang},
{(unsigned char*)"7364",(unsigned char*)"reng",(unsigned char*)PY_mb_reng},
{(unsigned char*)"7664",(unsigned char*)"rong",(unsigned char*)PY_mb_rong},
{(unsigned char*)"7826",(unsigned char*)"ruan",(unsigned char*)PY_mb_ruan},
{(unsigned char*)"7264",(unsigned char*)"sang",(unsigned char*)PY_mb_sang},
{(unsigned char*)"7364",(unsigned char*)"seng",(unsigned char*)PY_mb_seng},
{(unsigned char*)"7424",(unsigned char*)"shai",(unsigned char*)PY_mb_shai},
{(unsigned char*)"7426",(unsigned char*)"shan",(unsigned char*)PY_mb_shan},
{(unsigned char*)"7426",(unsigned char*)"shao",(unsigned char*)PY_mb_shao},
{(unsigned char*)"7434",(unsigned char*)"shei",(unsigned char*)PY_mb_shei},
{(unsigned char*)"7436",(unsigned char*)"shen",(unsigned char*)PY_mb_shen},    
{(unsigned char*)"7468",(unsigned char*)"shou",(unsigned char*)PY_mb_shou},
{(unsigned char*)"7482",(unsigned char*)"shua",(unsigned char*)PY_mb_shua},
{(unsigned char*)"7484",(unsigned char*)"shui",(unsigned char*)PY_mb_shui},
{(unsigned char*)"7486",(unsigned char*)"shun",(unsigned char*)PY_mb_shun},
{(unsigned char*)"7486",(unsigned char*)"shuo",(unsigned char*)PY_mb_shuo},
{(unsigned char*)"7664",(unsigned char*)"song",(unsigned char*)PY_mb_song},
{(unsigned char*)"7826",(unsigned char*)"suan",(unsigned char*)PY_mb_suan},
{(unsigned char*)"8264",(unsigned char*)"tang",(unsigned char*)PY_mb_tang},
{(unsigned char*)"8364",(unsigned char*)"teng",(unsigned char*)PY_mb_teng},
{(unsigned char*)"8426",(unsigned char*)"tian",(unsigned char*)PY_mb_tian},
{(unsigned char*)"8426",(unsigned char*)"tiao",(unsigned char*)PY_mb_tiao},
{(unsigned char*)"8464",(unsigned char*)"ting",(unsigned char*)PY_mb_ting},
{(unsigned char*)"8664",(unsigned char*)"tong",(unsigned char*)PY_mb_tong},
{(unsigned char*)"8826",(unsigned char*)"tuan",(unsigned char*)PY_mb_tuan},
{(unsigned char*)"9264",(unsigned char*)"wang",(unsigned char*)PY_mb_wang},
{(unsigned char*)"9364",(unsigned char*)"weng",(unsigned char*)PY_mb_weng},
{(unsigned char*)"9426",(unsigned char*)"xian",(unsigned char*)PY_mb_xian},
{(unsigned char*)"9426",(unsigned char*)"xiao",(unsigned char*)PY_mb_xiao},
{(unsigned char*)"9464",(unsigned char*)"xing",(unsigned char*)PY_mb_xing},
{(unsigned char*)"9826",(unsigned char*)"xuan",(unsigned char*)PY_mb_xuan},
{(unsigned char*)"9264",(unsigned char*)"yang",(unsigned char*)PY_mb_yang},
{(unsigned char*)"9464",(unsigned char*)"ying",(unsigned char*)PY_mb_ying},
{(unsigned char*)"9664",(unsigned char*)"yong",(unsigned char*)PY_mb_yong},
{(unsigned char*)"9826",(unsigned char*)"yuan",(unsigned char*)PY_mb_yuan},
{(unsigned char*)"9264",(unsigned char*)"zang",(unsigned char*)PY_mb_zang},
{(unsigned char*)"9364",(unsigned char*)"zeng",(unsigned char*)PY_mb_zeng},
{(unsigned char*)"9424",(unsigned char*)"zhai",(unsigned char*)PY_mb_zhai},
{(unsigned char*)"9426",(unsigned char*)"zhan",(unsigned char*)PY_mb_zhan},
{(unsigned char*)"9426",(unsigned char*)"zhao",(unsigned char*)PY_mb_zhao},
{(unsigned char*)"9436",(unsigned char*)"zhen",(unsigned char*)PY_mb_zhen},
{(unsigned char*)"9468",(unsigned char*)"zhou",(unsigned char*)PY_mb_zhou},
{(unsigned char*)"9482",(unsigned char*)"zhua",(unsigned char*)PY_mb_zhua},
{(unsigned char*)"9484",(unsigned char*)"zhui",(unsigned char*)PY_mb_zhui},
{(unsigned char*)"9486",(unsigned char*)"zhun",(unsigned char*)PY_mb_zhun},
{(unsigned char*)"9486",(unsigned char*)"zhuo",(unsigned char*)PY_mb_zhuo},
{(unsigned char*)"9664",(unsigned char*)"zong",(unsigned char*)PY_mb_zong},
{(unsigned char*)"9826",(unsigned char*)"zuan",(unsigned char*)PY_mb_zuan},
{(unsigned char*)"24264",(unsigned char*)"chang",(unsigned char*)PY_mb_chang},
{(unsigned char*)"24364",(unsigned char*)"cheng",(unsigned char*)PY_mb_cheng},
{(unsigned char*)"24664",(unsigned char*)"chong",(unsigned char*)PY_mb_chong},
{(unsigned char*)"24826",(unsigned char*)"chuan",(unsigned char*)PY_mb_chuan},
{(unsigned char*)"48264",(unsigned char*)"guang",(unsigned char*)PY_mb_guang},
{(unsigned char*)"48264",(unsigned char*)"huang",(unsigned char*)PY_mb_huang},
{(unsigned char*)"54264",(unsigned char*)"jiang",(unsigned char*)PY_mb_jiang},
{(unsigned char*)"54664",(unsigned char*)"jiong",(unsigned char*)PY_mb_jiong},
{(unsigned char*)"58264",(unsigned char*)"kuang",(unsigned char*)PY_mb_kuang},
{(unsigned char*)"54264",(unsigned char*)"liang",(unsigned char*)PY_mb_liang},
{(unsigned char*)"64264",(unsigned char*)"niang",(unsigned char*)PY_mb_niang},
{(unsigned char*)"74264",(unsigned char*)"qiang",(unsigned char*)PY_mb_qiang},
{(unsigned char*)"74664",(unsigned char*)"qiong",(unsigned char*)PY_mb_qiong},
{(unsigned char*)"74264",(unsigned char*)"shang ",(unsigned char*)PY_mb_shang},
{(unsigned char*)"74364",(unsigned char*)"sheng",(unsigned char*)PY_mb_sheng},
{(unsigned char*)"74824",(unsigned char*)"shuai",(unsigned char*)PY_mb_shuai},
{(unsigned char*)"74826",(unsigned char*)"shuan",(unsigned char*)PY_mb_shuan},
{(unsigned char*)"94264",(unsigned char*)"xiang",(unsigned char*)PY_mb_xiang},
{(unsigned char*)"94664",(unsigned char*)"xiong",(unsigned char*)PY_mb_xiong},
{(unsigned char*)"94264",(unsigned char*)"zhang",(unsigned char*)PY_mb_zhang},
{(unsigned char*)"94364",(unsigned char*)"zheng",(unsigned char*)PY_mb_zheng},
{(unsigned char*)"94664",(unsigned char*)"zhong",(unsigned char*)PY_mb_zhong},
{(unsigned char*)"94824",(unsigned char*)"zhuai",(unsigned char*)PY_mb_zhuai},
{(unsigned char*)"94826",(unsigned char*)"zhuan",(unsigned char*)PY_mb_zhuan},
{(unsigned char*)"248264",(unsigned char*)"chuang",(unsigned char*)PY_mb_chuang},
{(unsigned char*)"748264",(unsigned char*)"shuang",(unsigned char*)PY_mb_shuang},
{(unsigned char*)"948264",(unsigned char*)"zhuang",(unsigned char*)PY_mb_zhuang},
};

#endif
